#!/bin/bash

set -e

export CI_DIR=$1

LATTICE_DIR=$(cd `dirname $0` && cd ../../.. && pwd)
source $LATTICE_DIR/pipeline/local/env

export LATTICE_RELEASE_VERSION=v0.2.8

DOCKER_MOUNT_DIR=$CI_DIR/lattice $CI_DIR/lattice/pipeline/helpers/run_with_docker $LATTICE_SRC_PATH/pipeline/04_release/release $LATTICE_SRC_PATH/build/lattice.tgz
