// This file was generated by counterfeiter
package mocks

import (
	"net"
	"sync"

	"github.com/cloudfoundry-incubator/lattice/ltc/ssh/sshapi"
)

type FakeDialer struct {
	DialStub        func(n, addr string) (net.Conn, error)
	dialMutex       sync.RWMutex
	dialArgsForCall []struct {
		n    string
		addr string
	}
	dialReturns struct {
		result1 net.Conn
		result2 error
	}
}

func (fake *FakeDialer) Dial(n string, addr string) (net.Conn, error) {
	fake.dialMutex.Lock()
	fake.dialArgsForCall = append(fake.dialArgsForCall, struct {
		n    string
		addr string
	}{n, addr})
	fake.dialMutex.Unlock()
	if fake.DialStub != nil {
		return fake.DialStub(n, addr)
	} else {
		return fake.dialReturns.result1, fake.dialReturns.result2
	}
}

func (fake *FakeDialer) DialCallCount() int {
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	return len(fake.dialArgsForCall)
}

func (fake *FakeDialer) DialArgsForCall(i int) (string, string) {
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	return fake.dialArgsForCall[i].n, fake.dialArgsForCall[i].addr
}

func (fake *FakeDialer) DialReturns(result1 net.Conn, result2 error) {
	fake.DialStub = nil
	fake.dialReturns = struct {
		result1 net.Conn
		result2 error
	}{result1, result2}
}

var _ sshapi.Dialer = new(FakeDialer)
