#!/bin/bash

set -e

LATTICE_DIR=$(cd `dirname $0` && cd .. && pwd)

if [ ! -d $LATTICE_DIR/build ]; then
	echo "Please run development/setup before development/build"
	exit 1
fi

source $LATTICE_DIR/development/env

DOCKER_MOUNT_DIR=$LATTICE_DIR $LATTICE_DIR/pipeline/helpers/run_with_docker $LATTICE_SRC_PATH/pipeline/01_compilation/compile_lattice_tar
mv -v $LATTICE_DIR/build/lattice.tgz $LATTICE_DIR/
