#!/bin/bash

set -e

LATTICE_DIR=$(cd `dirname $0` && cd .. && pwd)

if [ ! -d $LATTICE_DIR/build ]; then
  echo "Please run development/setup before development/build"
  exit 1
fi

source $LATTICE_DIR/development/env

docker run --rm -a stdout -a stderr -w /lattice -v $LATTICE_DIR:/lattice cloudfoundry/lattice-pipeline \
  /lattice/cluster/scripts/compile /lattice/lattice.tgz 
