#!/bin/bash

set -e

LATTICE_DIR=$(cd `dirname $0` && cd .. && pwd)
DIEGO_VERSION=${1-`cat $LATTICE_DIR/DIEGO_VERSION`}

source $LATTICE_DIR/development/env

mkdir -p $LATTICE_DIR/build
pushd $LATTICE_DIR/build >/dev/null
  [ ! -d "cf-release" ] && git clone git@github.com:cloudfoundry/cf-release.git -b runtime-passed
  ( cd cf-release && ./update )

  if [ ! -d "diego-release" ]; then
    git clone git@github.com:cloudfoundry-incubator/diego-release.git -b "$DIEGO_VERSION"
  else
    rm -f diego-release/src/github.com/cloudfoundry-incubator/lattice
    ( cd diego-release && git reset --hard && git checkout "$DIEGO_VERSION" && git clean -xffd )
  fi
  ( cd diego-release && ./scripts/update )

  rm -rf $GOPATH/src/github.com/docker/docker
popd >/dev/null

go get github.com/dajulia3/godep
go get github.com/onsi/ginkgo/ginkgo
go get github.com/maxbrunsfeld/counterfeiter

pushd $GOPATH/src/github.com/cloudfoundry-incubator >/dev/null
  ln -sfh ../../../../.. lattice

  pushd lattice >/dev/null
    go get -v ./cell-helpers/...
  popd >/dev/null

  pushd lattice/ltc >/dev/null
    godep restore
    go install
  popd >/dev/null
popd >/dev/null

docker pull $DOCKER_IMAGE
docker pull cloudfoundry/lattice-app
