#!/bin/bash

set -e

LATTICE_DIR=$(cd `dirname $0` && cd .. && pwd)

DIEGO_VERSION=${1-`cat $LATTICE_DIR/DIEGO_VERSION`}
GARDEN_LINUX_VERSION=${2-`cat $LATTICE_DIR/GARDEN_LINUX_VERSION`}
CF_VERSION=${3-`cat $LATTICE_DIR/CF_VERSION`}
ROUTING_VERSION=${4-`cat $LATTICE_DIR/ROUTING_VERSION`}

update() {
  REPO_PATH=`basename $1`

  if [ ! -d "$REPO_PATH" ]; then
    git clone "git@github.com:$1"
    ( cd $REPO_PATH && git checkout $2 )
  else
    pushd "$REPO_PATH" >/dev/null
      git fetch
      git reset --hard
      git checkout "$2"
      git clean -xffd
    popd >/dev/null
  fi
}

source $LATTICE_DIR/development/env

mkdir -p $LATTICE_DIR/build
pushd $LATTICE_DIR/build >/dev/null
  rm -f diego-release/src/github.com/cloudfoundry-incubator/lattice

  update cloudfoundry-incubator/diego-release "$DIEGO_VERSION"
  ( cd diego-release && ./scripts/update )

  update cloudfoundry-incubator/garden-linux-release "$GARDEN_LINUX_VERSION"
  ( cd garden-linux-release && git submodule update --init --recursive )

  update cloudfoundry/cf-release "$CF_VERSION"
  ( cd cf-release && ./update )

  update cloudfoundry-incubator/cf-routing-release "$ROUTING_VERSION"
  ( cd cf-routing-release && ./scripts/update )

  rm -rf $GOPATH/src/github.com/docker/docker
popd >/dev/null

go get github.com/tools/godep
go get github.com/onsi/ginkgo/ginkgo
go get github.com/maxbrunsfeld/counterfeiter

pushd $GOPATH/src/github.com/cloudfoundry-incubator >/dev/null
  ln -sfh ../../../../.. lattice

  pushd lattice/cell-helpers >/dev/null
    godep restore
    go install ./davtool/
    go install ./s3tool/
    go install ./tee2metron/
  popd >/dev/null

  pushd lattice/ltc >/dev/null
    godep restore 2>/dev/null || godep restore  # for docker...
    go install
  popd >/dev/null
popd >/dev/null

docker pull cloudfoundry/lattice-pipeline
docker pull cloudfoundry/lattice-app
