#!/bin/bash

set -e

echo "Running ssh-agent"
eval `ssh-agent`

diego_edge_tar_path=$1

upload_diego_edge_to_s3() {
    echo "upload to s3"
    aws s3 cp $diego_edge_tar_path s3://diego-edge/diego-edge-latest.box

    box_url="http://diego-edge.s3.amazonaws.com/diego-edge-latest.box"
    echo $box_url
}

upload_diego_edge_to_s3

aws s3 cp s3://diego-lite-gocd/credentials/ci_key ci_key
ssh-add -D
chmod 700 ci_key
ssh-add ci_key

pushd diego-lite
    git pull origin master
    git co master
    echo "merging develop onto master"
    git merge develop

    echo "pushing local master to origin/master"
    git push origin master
    echo "Successfully pushed updates to origin/master"
popd
