#!/bin/bash

set -e -x
echo "Running ssh-agent"
eval `ssh-agent`
diego_edge_tar_path=$1

upload_diego_edge_to_s3() {
    echo "upload to s3"
    aws s3 cp $diego_edge_tar_path "s3://diego-edge/diego-edge-latest.tgz"
    aws s3 cp $diego_edge_tar_path "s3://diego-edge/diego-edge-$new_diego_edge_version.tgz"
    aws s3 cp diego-lite/Version "s3://diego-edge/Version"

    diego_edge_s3_url="http://diego-edge.s3.amazonaws.com/diego-edge-latest.tgz"
    echo $diego_edge_s3_url
}

previous_diego_edge_version=`cat diego-lite/Version`
new_diego_edge_version=$((previous_diego_edge_version+1))

echo "Updating Version file: $previous_diego_edge_version -> $new_diego_edge_version"
echo $new_diego_edge_version > diego-lite/Version

upload_diego_edge_to_s3

aws s3 cp s3://diego-lite-gocd/credentials/ci_key ci_key
chmod 700 ci_key
ssh-add ci_key

pushd diego-lite
    git add Version
    git commit -m "Bump Version: $previous_diego_edge_version -> $new_diego_edge_version"
    git pull origin master
    git checkout master
    echo "merging develop onto master"
    git merge develop
    echo "pushing local master to origin/master"
    git push origin master
    echo "Successfully pushed updates to origin/master"

    echo "pushing local develop to origin/develop"
    git push origin develop
    echo "Successfully pushed updates to origin/develop"
popd
