#!/bin/sh

set -e -x

docker pull $DOCKER_IMAGE
docker run -a stdout -a stderr -w /workspace \
  -v `pwd`:/workspace \
  -e VAGRANT_CLOUD_ACCESS_TOKEN \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  $DOCKER_IMAGE \
  /bin/bash -l diego-lite/diego-lite-pipeline/03_promote_and_publish/promote_and_publish

pushd diego-lite
    sed -i -e "s/config.vm.box_version = '.*'/config.vm.box_version = '$next_version_number'/" Vagrantfile
    git diff
    git add Vagrantfile
    git commit -m "Update vagrant box version to ${next_version_number}"
    git push origin HEAD:master

    git fetch origin develop
    git merge origin/develop -m "Merge build ${BOSH_LITE_CANDIDATE_BUILD_NUMBER} to develop"
    git push origin HEAD:develop
popd
