#!/bin/sh

set -e -x

docker pull $DOCKER_IMAGE
docker run -a stdout -a stderr -w /workspace \
  -v `pwd`:/workspace \
  -e VAGRANT_CLOUD_ACCESS_TOKEN \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  $DOCKER_IMAGE \
  /bin/bash -l diego-lite/diego-lite-pipeline/03_promote_and_publish/promote_and_publish
