#!/bin/bash

set -e

lattice_version=$(< /var/lattice/LATTICE_VERSION)

echo "Installing Lattice ($lattice_version) - Lattice Cell"

lattice_cell_build_path=/tmp/lattice-build/lattice-cell

install_dependencies() {
    echo "Installing Dependencies..."
    pushd /tmp
        SHADOW_TAR_OBJECT_ID="8f17023f-2a94-4d98-a737-ddbf166e7188"
        wget "http://go-diego-go.s3.amazonaws.com/${SHADOW_TAR_OBJECT_ID}" -O - | tar xzf -
        pushd shadow-4.2.1
            ./configure --prefix=/var/lattice
            make
            make install
        popd
    popd
}

#-n so we don't overwrite the coordinator upstart scripts in collocated installation.
#In collocated, Consul should run only in server mode and not use the lattice-cell consul upstart which is client-only mode
cp -nv $lattice_cell_build_path/upstart/* /etc/init
cp -nv $lattice_cell_build_path/bin/* /usr/local/bin
cp -av $lattice_cell_build_path/cell_health_check /var/lattice

mkdir -pv /var/lattice/garden
mkdir -pv /var/lattice/garden/depot
mkdir -pv /var/lattice/garden/rootfs
mkdir -pv /var/lattice/garden/overlays
mkdir -pv /var/lattice/garden/graph

cp -av $lattice_cell_build_path/garden/garden-bin /var/lattice/garden/garden-bin
cp -av $lattice_cell_build_path/garden/skeleton /var/lattice/garden/skeleton

mkdir -pv /var/lattice/config
cp -anv $lattice_cell_build_path/config /var/lattice

apt-get -y install gcc
apt-get -y install make
apt-get -y install quota
apt-get -y install linux-image-extra-$(uname -r)

mkdir -pv /var/lattice/run
mkdir -pv /var/lattice/log

install_dependencies &> /var/lattice/log/lattice-cell-install.log
start bootstrap

echo "Finished Installing Lattice Cell ($lattice_version)!" 
