// This file was generated by counterfeiter
package fake_channel_listener

import (
	"net"
	"sync"

	"github.com/cloudfoundry-incubator/lattice/ltc/secure_shell"
)

type FakeChannelListener struct {
	ListenStub        func(net, laddr string) (<-chan net.Conn, <-chan error)
	listenMutex       sync.RWMutex
	listenArgsForCall []struct {
		net   string
		laddr string
	}
	listenReturns struct {
		result1 <-chan net.Conn
		result2 <-chan error
	}
}

func (fake *FakeChannelListener) Listen(net string, laddr string) (<-chan net.Conn, <-chan error) {
	fake.listenMutex.Lock()
	fake.listenArgsForCall = append(fake.listenArgsForCall, struct {
		net   string
		laddr string
	}{net, laddr})
	fake.listenMutex.Unlock()
	if fake.ListenStub != nil {
		return fake.ListenStub(net, laddr)
	} else {
		return fake.listenReturns.result1, fake.listenReturns.result2
	}
}

func (fake *FakeChannelListener) ListenCallCount() int {
	fake.listenMutex.RLock()
	defer fake.listenMutex.RUnlock()
	return len(fake.listenArgsForCall)
}

func (fake *FakeChannelListener) ListenArgsForCall(i int) (string, string) {
	fake.listenMutex.RLock()
	defer fake.listenMutex.RUnlock()
	return fake.listenArgsForCall[i].net, fake.listenArgsForCall[i].laddr
}

func (fake *FakeChannelListener) ListenReturns(result1 <-chan net.Conn, result2 <-chan error) {
	fake.ListenStub = nil
	fake.listenReturns = struct {
		result1 <-chan net.Conn
		result2 <-chan error
	}{result1, result2}
}

var _ secure_shell.ChannelListener = new(FakeChannelListener)
