branches:
  only:
    - develop
    - master

language: go
go:
- 1.2
- 1.3
- 1.4
- tip
matrix:
  allow_failures:
    - go: 1.2
    - go: 1.3
    - go: tip

before_install:
- 'if [[ "${TRAVIS_GO_VERSION}" =~ 1.[2-3] ]]; then go get code.google.com/p/go.tools/cmd/cover; else go get golang.org/x/tools/cmd/cover; fi'
- go get -v github.com/tools/godep
- go get -v github.com/onsi/ginkgo/ginkgo
- go get -v github.com/mattn/goveralls
after_success:
- pushd ltc
- 'echo "mode: set" > coverage.out'
- 'find . -name "*.coverprofile" -exec grep -v mode: {} >> coverage.out \;'
- PATH=$HOME/gopath/bin:$PATH goveralls -coverprofile=coverage.out -repotoken=$COVERALLS_TOKEN
- popd

install:
- pushd ltc
- PATH=$HOME/gopath/bin:$PATH godep restore
- popd

script:
- pushd ltc
- PATH=$HOME/gopath/bin:$PATH ginkgo -r --race --randomizeAllSpecs --failOnPending --skipMeasurements --cover
- test -z "$(go fmt ./...)"
- popd
