#!/bin/bash

set -e

export DIEGO_RELEASE_PATH=$1
export CF_RELEASE_PATH=$2

export GOOS=linux
export GOARCH=amd64

rm -rf bin/*
export GOBIN=/vagrant/bin
export GOPATH=$DIEGO_RELEASE_PATH

rm -rf $GOPATH/pkg/*

pushd $GOPATH
    go install github.com/cloudfoundry-incubator/rep/cmd/rep
    go install github.com/cloudfoundry-incubator/executor/cmd/executor
    go install github.com/cloudfoundry-incubator/auctioneer/cmd/auctioneer
    go install github.com/cloudfoundry-incubator/converger/cmd/converger
    go install github.com/cloudfoundry-incubator/route-emitter/cmd/route-emitter
    go install github.com/cloudfoundry-incubator/garden-linux
    go install github.com/apcera/gnatsd
    go install github.com/cloudfoundry-incubator/receptor/cmd/receptor
    go install github.com/cloudfoundry-incubator/file-server/cmd/file-server
    go install github.com/cloudfoundry-incubator/docker-circus/spy

    pushd src/github.com/coreos/etcd
        ./build
        cp bin/etcd $GOBIN
    popd
popd

pushd $CF_RELEASE_PATH/src
    GOPATH=/tmp/go
    mkdir -p $GOPATH/src/github.com/cloudfoundry

    REPO_NAME=github.com/cloudfoundry/gorouter
    cp -fr gorouter $GOPATH/src/$REPO_NAME

    GOPATH=$GOPATH/src/${REPO_NAME}/Godeps/_workspace:$GOPATH
    go install github.com/cloudfoundry/gorouter
    rm -rf $GOPATH
    GOPATH=$DIEGO_RELEASE_PATH
popd

pushd $DIEGO_RELEASE_PATH/loggregator
    GOPATH=`pwd`
    go install trafficcontroller
    go install doppler
    go install metron
popd
