#!/bin/bash

set -e

compile_garden_linux() {
    mkdir -p $OUTPUT_DIR/lattice-cell/garden

    GOPATH=$GOPATH/src/github.com/cloudfoundry-incubator/garden-linux/Godeps/_workspace:$GOPATH
    go install -tags daemon github.com/cloudfoundry-incubator/garden-linux
    GOPATH=$DIEGO_RELEASE_PATH

    pushd $DIEGO_RELEASE_PATH/src/github.com/cloudfoundry-incubator/garden-linux/old
        make

        cp -a linux_backend/bin $OUTPUT_DIR/lattice-cell/garden/garden-bin
        cp -a linux_backend/skeleton $OUTPUT_DIR/lattice-cell/garden/skeleton
    popd
}

compile_gorouter() {
    pushd $CF_RELEASE_PATH/src
        GOPATH=/tmp/go
        mkdir -p $GOPATH/src/github.com/cloudfoundry

        REPO_NAME=github.com/cloudfoundry/gorouter
        cp -fr gorouter $GOPATH/src/$REPO_NAME

        GOPATH=$GOPATH/src/${REPO_NAME}/Godeps/_workspace:$GOPATH
        go install github.com/cloudfoundry/gorouter
        rm -rf $GOPATH
        GOPATH=$DIEGO_RELEASE_PATH
    popd
}

compile_coordinator_loggregator() {
    pushd $CF_RELEASE_PATH/src/loggregator
        GOPATH=`pwd`
        go install trafficcontroller
        go install doppler
        GOPATH=$DIEGO_RELEASE_PATH
    popd
}

compile_lattice_cell_loggregator() {
    pushd $CF_RELEASE_PATH/src/loggregator
        GOPATH=`pwd`
        go install metron
        GOPATH=$DIEGO_RELEASE_PATH
    popd
}


compile_lattice-cell() {
    export GOBIN=$OUTPUT_DIR/lattice-cell/bin

    pushd $GOPATH
        go install github.com/cloudfoundry-incubator/rep/cmd/rep
        go install github.com/cloudfoundry-incubator/executor/cmd/executor
        go install github.com/cloudfoundry-incubator/auctioneer/cmd/auctioneer
        go install github.com/cloudfoundry-incubator/converger/cmd/converger
    popd

    compile_garden_linux
    compile_lattice_cell_loggregator

    CONSUL_OBJECT_ID="bb8108ec-b026-4ce4-8216-0fabfeaac904"
    wget "http://go-diego-go.s3.amazonaws.com/${CONSUL_OBJECT_ID}" -O $GOBIN/consul
    chmod +x $GOBIN/consul

    cp -av $LATTICE_PATH/lattice-cell/ $OUTPUT_DIR/
}

compile_coordinator() {
    export GOBIN=$OUTPUT_DIR/coordinator/bin

    pushd $GOPATH
        go install github.com/cloudfoundry-incubator/route-emitter/cmd/route-emitter
        go install github.com/apcera/gnatsd
        go install github.com/cloudfoundry-incubator/receptor/cmd/receptor
        go install github.com/cloudfoundry-incubator/file-server/cmd/file-server
        go install github.com/cloudfoundry-incubator/docker-circus/spy

        pushd src/github.com/coreos/etcd
            ./build
            cp bin/etcd $GOBIN
        popd
    popd

    compile_gorouter
    compile_coordinator_loggregator

    CONSUL_OBJECT_ID="bb8108ec-b026-4ce4-8216-0fabfeaac904"
    wget "http://go-diego-go.s3.amazonaws.com/${CONSUL_OBJECT_ID}" -O $GOBIN/consul
    chmod +x $GOBIN/consul

    cp -av $LATTICE_PATH/coordinator/ $OUTPUT_DIR/
}

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    echo "Incorrect Usage. Usage: $0 output-dir diego-release-path cf-release-path lattice-path"
    exit 1
fi

export OUTPUT_DIR=$1
export DIEGO_RELEASE_PATH=$2
export CF_RELEASE_PATH=$3
export LATTICE_PATH=$4
export GOOS=linux
export GOARCH=amd64
export GOPATH=$DIEGO_RELEASE_PATH

rm -rf $OUTPUT_DIR/*
rm -rf $GOPATH/pkg/*

mkdir -pv $LATTICE_PATH/common
cp -av $LATTICE_PATH/common/* $OUTPUT_DIR/common/

compile_lattice-cell
compile_coordinator
