#!/bin/bash

set -e

COMPONENT_TO_INSTALL=$1
PATH_TO_LATTICE_TAR=$2
LATTICE_TAR_URL=$3

if [ $COMPONENT_TO_INSTALL != "lattice-cell" ] && [ $COMPONENT_TO_INSTALL != "coordinator" ] && [ $COMPONENT_TO_INSTALL != "collocated" ]; then
    echo "Incorrect Usage. Must install either lattice-cell or coordinator or both.
    Usage: install_from_tar lattice-cell [LATTICE_TAR_PATH] OR
           install_from_tar coordinator [LATTICE_TAR_PATH]
           install_from_tar collocated [LATTICE_TAR_PATH]
    "
    exit 2
fi

if [ -z "${PATH_TO_LATTICE_TAR}" ] && [ -n "${LATTICE_TAR_URL}" ]; then
    PATH_TO_LATTICE_TAR=/tmp/lattice.tgz
    echo -n "Downloading $LATTICE_TAR_URL .."
    wget $LATTICE_TAR_URL --quiet -O $PATH_TO_LATTICE_TAR && echo "DONE!"
    ## TODO: check for 404, default to latest unstable build
elif [ -z "${PATH_TO_LATTICE_TAR}" ]; then
    PATH_TO_LATTICE_TAR=/tmp/lattice.tgz
    LATTICE_TAR_URL="https://s3-us-west-2.amazonaws.com/lattice/unstable/latest/lattice.tgz"
    echo -n "Downloading $LATTICE_TAR_URL .."
    wget $LATTICE_TAR_URL --quiet -O $PATH_TO_LATTICE_TAR && echo "DONE!"
fi

tar -xf $PATH_TO_LATTICE_TAR -C /tmp

/tmp/lattice-build/common/install-common

if [ $COMPONENT_TO_INSTALL == "collocated" ]; then
    /tmp/lattice-build/coordinator/install-coordinator

    #Stop consul and bootstrap in collocated install so we can trigger dependencies to fire off the single bootstrap script
    #once the cell is installed too.
    stop consul
    stop bootstrap

    sleep 2

    /tmp/lattice-build/lattice-cell/install-lattice-cell
else
    /tmp/lattice-build/$COMPONENT_TO_INSTALL/install-$COMPONENT_TO_INSTALL
fi

