#!/bin/bash

set -e

PATH_TO_LATTICE_TAR=$1
if [ -z "${PATH_TO_LATTICE_TAR}" ]; then
  echo "Downloading latest Diego Edge Release tar"
  PATH_TO_LATTICE_TAR=/tmp/lattice-latest.tgz

  LATTICE_LATEST=https://s3-us-west-2.amazonaws.com/lattice/lattice-latest.tgz
  wget --quiet $LATTICE_LATEST -O $PATH_TO_LATTICE_TAR
fi

tar -xf $PATH_TO_LATTICE_TAR -C /tmp

/tmp/lattice-build/install /tmp/lattice-build/
