#!/bin/bash

set -e

docker pull ubuntu:trusty
docker build --force-rm --no-cache -t $DOCKER_IMAGE diego-edge/diego_edge_dependencies_pipeline/02_publish_pipeline_docker_image/pipeline_image/
docker push $DOCKER_IMAGE
