#!/bin/bash

set -e
## Assumes AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set.

export CI_DIR=$1

LATTICE_DIR=$(cd `dirname $0` && cd ../../.. && pwd)
source $LATTICE_DIR/pipeline/local/env

DOCKER_MOUNT_DIR=$CI_DIR/lattice $CI_DIR/lattice/pipeline/helpers/run_with_docker $LATTICE_SRC_PATH/pipeline/02_test/run_gce_whetstone 

