#!/bin/bash
set -e

if [[ -z "$LATTICE_SRC_PATH" ]] || [[ -z "$DIEGO_RELEASE_PATH" ]]; then
    echo "Must set LATTICE_SRC_PATH and DIEGO_RELEASE_PATH"
    exit 1
fi

source $(dirname $0)/../helpers/build_ltc_helpers

setup_go_env

construct_ltc_gopath

run_unit_tests

git_describe_lattice

go_build_ltc

generate_ltc_tarball "/workspace"

