#!/bin/bash
set -e

if [ -z "$LATTICE_SRC_PATH" ]; then
    echo "Must set LATTICE_SRC_PATH"
    exit 1
fi

if [ -z "$DIEGO_RELEASE_PATH" ]; then
    echo "Must set DIEGO_RELEASE_PATH"
    exit 1
fi

mkdir ~/go
export GOPATH=~/go
export PATH="$PATH:$GOPATH/bin"

$LATTICE_SRC_PATH/lattice-pipeline/helpers/construct_ltc_gopath

go install github.com/onsi/ginkgo/ginkgo

echo "Running ltc unit tests..."
$GOPATH/src/github.com/cloudfoundry-incubator/lattice/ltc/scripts/test

pushd $LATTICE_SRC_PATH > /dev/null
    version_from_file=$(<LATTICE_VERSION)
popd > /dev/null

echo -n "Compiling cli ($version_from_file) .."
OUTDIR="$HOME/compiled-binaries"
mkdir -p $OUTDIR && sync
export GOBIN="$OUTDIR"

GOARCH=amd64 GOOS=linux go build \
    -ldflags "-X github.com/cloudfoundry-incubator/lattice/ltc/setup_cli.latticeVersion $version_from_file" \
    -o $OUTDIR/ltc-linux-amd64 \
    github.com/cloudfoundry-incubator/lattice/ltc

GOARCH=amd64 GOOS=darwin go build \
    -ldflags "-X github.com/cloudfoundry-incubator/lattice/ltc/setup_cli.latticeVersion $version_from_file" \
    -o $OUTDIR/ltc-darwin-amd64 \
    github.com/cloudfoundry-incubator/lattice/ltc

echo "DONE!"

echo -n "Generating ltc-checksum = "
pushd $LATTICE_SRC_PATH > /dev/null
    git rev-parse HEAD | tee $OUTDIR/ltc-checksum  #TODO: Do we even use the ltc-checksum anymore?
popd > /dev/null
sync

echo -n "Creating ltc ($version_from_file) tarball .."
pushd $OUTDIR > /dev/null
    rm -f /workspace/ltc.tar.gz
    tar czf /workspace/ltc.tar.gz ltc* && echo "SUCCESS!"
popd > /dev/null
