#!/bin/bash
set -e

cleanup_vagrant() {
    pushd diego-lite/diego-lite-pipeline/02_test
        vagrant ssh -c "pushd /var/log tar -czf /vagrant/vagrant_upstart_logs.tgz upstart"
        vagrant destroy --force
    popd

    mv diego-lite/diego-lite-pipeline/02_test/vagrant_upstart_logs.tgz .

    vagrant box remove --force diego-lite-in-progress
}

trap cleanup_vagrant EXIT

vagrant box add diego-lite.box --name diego-lite-in-progress

pushd diego-lite/diego-lite-pipeline/02_test
    vagrant up  --provider=virtualbox
popd

export DIEGO_RELEASE_PATH=$1
export GOPATH=$DIEGO_RELEASE_PATH

rm -rf $GOPATH/pkg/*

mkdir -p $GOPATH/src/github.com/pivotal-cf-experimental

ln -sf `pwd`/whetstone $GOPATH/src/github.com/pivotal-cf-experimental/

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

PATH=$PATH:$GOPATH/bin ginkgo -noColor $GOPATH/src/github.com/pivotal-cf-experimental/whetstone -- -domain="192.168.11.11.xip.io" -loggregatorAddress="loggregator.192.168.11.11.xip.io" -receptorAddress="receptor.192.168.11.11.xip.io" -timeout=300

