---
platform: linux
image: docker:///cloudfoundry/lattice-pipeline
inputs:
- name: lattice
- name: lattice-tar-experimental
- name: ltc-tar-experimental
run:
  path: lattice/concourse/tasks/cluster-test-terraform-aws/run.sh
  params:
    AWS_ACCESS_KEY_ID: some-access-key-id
    AWS_SECRET_ACCESS_KEY: some-secret-access-key
    AWS_SSH_PRIVATE_KEY: some-ssh-private-key
