#!/bin/bash

set -e

echo "Installing Lattice - Diego Cell"

lattice_diego_cell_build_path=/tmp/lattice-build/diego-cell

install_dependencies() {
    echo "Installing Dependencies..."
    pushd /tmp
        SHADOW_TAR_OBJECT_ID="8f17023f-2a94-4d98-a737-ddbf166e7188"
        wget "http://go-diego-go.s3.amazonaws.com/${SHADOW_TAR_OBJECT_ID}" -O - | tar xzf -
        pushd shadow-4.2.1
            ./configure --prefix=/var/lattice
            make
            make install
        popd
    popd
}

cp $lattice_diego_cell_build_path/upstart/* /etc/init
cp -n $lattice_diego_cell_build_path/bin/* /usr/local/bin

mkdir -p /var/lattice/garden
mkdir -p /var/lattice/garden/depot
mkdir -p /var/lattice/garden/rootfs
mkdir -p /var/lattice/garden/overlays
mkdir -p /var/lattice/garden/graph

cp -a $lattice_diego_cell_build_path/garden/garden-bin /var/lattice/garden/garden-bin
cp -a $lattice_diego_cell_build_path/garden/skeleton /var/lattice/garden/skeleton

mkdir -p /var/lattice/config
cp -a $lattice_diego_cell_build_path/config /var/lattice

apt-get -y install gcc
apt-get -y install make
apt-get -y install quota
apt-get -y install linux-image-extra-$(uname -r)

mkdir -p /var/lattice/run
mkdir -p /var/lattice/log

install_dependencies &> /var/lattice/log/diego-cell-install.log
start bootstrap

echo "Finished Installing Lattice Diego-Cell!"

