#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "Incorrect Usage. Usage: $0 /path/to/lattice.tgz"
    exit 1
fi

LATTICE_TGZ=$1

export $(cat /var/lattice/network)

/etc/init.d/lighttpd stop
mkdir -p /var/lattice/lighttpd/blobs
cat > /var/lattice/lighttpd/proxyconf.json <<JSON
{
    "http_proxy": $(echo $http_proxy | jq -R .),
    "https_proxy": $(echo $https_proxy | jq -R .),
    "no_proxy": $(echo $no_proxy | jq -R .)
}
JSON
chown -R www-data:www-data /var/lattice/lighttpd
echo $(cat /var/lattice/username):$(openssl passwd -crypt `cat /var/lattice/password`) > /var/lattice/lighttpd.user

tar xzf "$LATTICE_TGZ" --strip-components 2 --keep-directory-symlink --no-overwrite-dir --no-same-owner -C / -- ./root

ln -sf /var/vcap/jobs/receptor/monit /var/vcap/monit/job/0019_receptor.monitrc

perl -p -i -e "s/placeholder-system-domain/$SYSTEM_DOMAIN/g" `find /var/vcap/data/jobs -type f ! -wholename '/var/vcap/data/jobs/rootfses/*'`

/etc/init.d/lighttpd start
ln -snf /etc/sv/monit /etc/service/monit
