#!/bin/bash

LATTICE_VAGRANT_DIR=$(cd `dirname $0` && pwd)
PACKER_BOSH=$LATTICE_VAGRANT_DIR/assets/packer-bosh

curl -s http://lattice.s3.amazonaws.com/packer-bosh-assets.tgz | tar -C "$LATTICE_VAGRANT_DIR" -xz

if [ ! -f $HOME/.packerconfig ]; then
  echo '{"provisioners": {"packer-bosh":"'$PACKER_BOSH'"}}' >$HOME/.packerconfig
fi
bosh create release releases/diego/diego-0.1433.0.yml --with-tarball --dir ../diego-release
bosh create release releases/garden-linux/garden-linux-0.306.0.yml --with-tarball --dir ../garden-linux-release
bosh create release releases/cf-routing/cf-routing-0.99.0.yml --with-tarball --dir ../cf-routing-release
bosh create release releases/cf/cf-218.yml --with-tarball --dir ../cf-release

packer build $LATTICE_VAGRANT_DIR/lattice.json
