#!/bin/bash

set -e

LATTICE_RELEASE_DIR=$(cd `dirname $0` && cd .. && pwd)

curl -s http://lattice.s3.amazonaws.com/packer-bosh-assets.tgz | tar -C "$LATTICE_RELEASE_DIR/vagrant/" -xz

if [ ! -f $HOME/.packerconfig ]; then
  PACKER_BOSH=$LATTICE_RELEASE_DIR/vagrant/assets/packer-bosh
  echo '{"provisioners": {"packer-bosh":"'$PACKER_BOSH'"}}' >$HOME/.packerconfig
fi

rm -rf $LATTICE_RELEASE_DIR/vagrant/assets/{releases,versions}
mkdir $LATTICE_RELEASE_DIR/vagrant/assets/{releases,versions}

git -C "$LATTICE_RELEASE_DIR" describe --tags --always > $LATTICE_RELEASE_DIR/vagrant/assets/versions/LATTICE_RELEASE_IMAGE

for RELEASE in diego garden-linux cf-routing; do
  pushd $LATTICE_RELEASE_DIR/$RELEASE-release
    yes yes | bosh reset release
    bosh create release --name $RELEASE --version 0 --with-tarball --force
    VERSION_FILE="$(echo ${RELEASE//-/_} | tr [:lower:] [:upper:])_RELEASE"
    git describe --tags --always > $LATTICE_RELEASE_DIR/vagrant/assets/versions/$VERSION_FILE
  popd
done

pushd $LATTICE_RELEASE_DIR/vagrant/assets/releases
  cp $LATTICE_RELEASE_DIR/vagrant/cf-lattice.yml ./
  bosh create release $PWD/cf-lattice.yml --dir $LATTICE_RELEASE_DIR/cf-release --with-tarball --force

  mv $LATTICE_RELEASE_DIR/diego-release/dev_releases/diego/diego-0.tgz \
     $LATTICE_RELEASE_DIR/garden-linux-release/dev_releases/garden-linux/garden-linux-0.tgz \
     $LATTICE_RELEASE_DIR/cf-routing-release/dev_releases/cf-routing/cf-routing-0.tgz \
     ./
popd

packer build -only=virtualbox-iso $LATTICE_RELEASE_DIR/vagrant/lattice.json
