#!/bin/bash

set -e

compile_garden_linux() {
    mkdir -p $OUTPUT_DIR/cell/garden
    rm -rf $GOPATH/pkg/*

    rm -rf $GOPATH/src/github.com/cloudfoundry-incubator/garden-linux/Godeps/_workspace/pkg/*

    GOPATH=$GOPATH/src/github.com/cloudfoundry-incubator/garden-linux/Godeps/_workspace:$GOPATH
    echo "GOPATH=$GOPATH"

    go install -v -tags daemon github.com/cloudfoundry-incubator/garden-linux
    GOPATH=$DIEGO_RELEASE_PATH

    pushd $DIEGO_RELEASE_PATH/src/github.com/cloudfoundry-incubator/garden-linux/old
        make

        cp -a linux_backend/bin $OUTPUT_DIR/cell/garden/garden-bin
        cp -a linux_backend/skeleton $OUTPUT_DIR/cell/garden/skeleton
    popd

    rm -rf $GOPATH/pkg/*
}

compile_gorouter() {
    pushd $CF_RELEASE_PATH/src
        GOPATH=/tmp/go
        mkdir -p $GOPATH/src/github.com/cloudfoundry

        REPO_NAME=github.com/cloudfoundry/gorouter
        cp -fr gorouter $GOPATH/src/$REPO_NAME

        rm -rf $GOPATH/src/${REPO_NAME}/Godeps/_workspace/pkg
        GOPATH=$GOPATH/src/${REPO_NAME}/Godeps/_workspace:$GOPATH
        go install github.com/cloudfoundry/gorouter
        rm -rf $GOPATH
        GOPATH=$DIEGO_RELEASE_PATH
    popd
}

compile_brain_loggregator() {
    pushd $CF_RELEASE_PATH/src/loggregator
        GOPATH=`pwd`
        go install trafficcontroller
        go install doppler
        go install metron
        GOPATH=$DIEGO_RELEASE_PATH
    popd
}

compile_cell_loggregator() {
    pushd $CF_RELEASE_PATH/src/loggregator
        GOPATH=`pwd`
        go install metron
        GOPATH=$DIEGO_RELEASE_PATH
    popd
}

stage_common() {
    mkdir -pv $OUTPUT_DIR/common
    cp -av $LATTICE_PATH/cluster/common/* $OUTPUT_DIR/common/
    cp -v $LATTICE_PATH/Version $OUTPUT_DIR/common/LATTICE_VERSION
}

stage_scripts() {
    mkdir -pv $OUTPUT_DIR/scripts
    cp -av $LATTICE_PATH/cluster/scripts/* $OUTPUT_DIR/scripts/
}

compile_cell() {
    export GOBIN=$OUTPUT_DIR/cell/bin
    compile_garden_linux

    pushd $GOPATH
        go install github.com/cloudfoundry-incubator/rep/cmd/rep
        go install github.com/cloudfoundry-incubator/executor/cmd/executor
        go install github.com/cloudfoundry-incubator/auctioneer/cmd/auctioneer
        go install github.com/cloudfoundry-incubator/converger/cmd/converger
        go install github.com/cloudfoundry-incubator/lattice/tee2metron
    popd

    rm -rf $GOPATH/pkg/*

    compile_cell_loggregator

    CONSUL_OBJECT_ID="3e6c1e47-95a5-45ef-aeec-2cb4cc4c529a"
    wget "http://blob.cfblob.com/${CONSUL_OBJECT_ID}" -O $GOBIN/consul.zip
    pushd $GOBIN
        unzip consul.zip
        chmod +x $GOBIN/consul
        rm -vf consul.zip
    popd

    cp -av $LATTICE_PATH/cluster/cell/ $OUTPUT_DIR/
}

compile_brain() {
    export GOBIN=$OUTPUT_DIR/brain/bin

    pushd $GOPATH
        go install github.com/cloudfoundry-incubator/route-emitter/cmd/route-emitter
        go install github.com/apcera/gnatsd
        go install github.com/cloudfoundry-incubator/receptor/cmd/receptor
        go install github.com/cloudfoundry-incubator/file-server/cmd/file-server
        go install github.com/cloudfoundry-incubator/buildpack_app_lifecycle/healthcheck

        pushd src/github.com/coreos/etcd
            ./build
            cp bin/etcd $GOBIN
        popd
    popd

    rm -rf $GOPATH/pkg

    compile_gorouter
    compile_brain_loggregator

    CONSUL_OBJECT_ID="3e6c1e47-95a5-45ef-aeec-2cb4cc4c529a"
    wget "http://blob.cfblob.com/${CONSUL_OBJECT_ID}" -O $GOBIN/consul.zip
    pushd $GOBIN
        unzip consul.zip
        chmod +x $GOBIN/consul
        rm -vf consul.zip
    popd

    cp -av $LATTICE_PATH/cluster/brain/ $OUTPUT_DIR/
}

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    echo "Incorrect Usage. Usage: $0 output-dir diego-release-path cf-release-path lattice-path"
    exit 1
fi

export OUTPUT_DIR=$1
export DIEGO_RELEASE_PATH=$2
export CF_RELEASE_PATH=$3
export LATTICE_PATH=$4
export GOOS=linux
export GOARCH=amd64
export GOPATH=$DIEGO_RELEASE_PATH

echo "DIEGO_RELEASE_PATH=$DIEGO_RELEASE_PATH"
echo "CF_RELEASE_PATH=$CF_RELEASE_PATH"
echo "LATTICE_PATH=$LATTICE_PATH"
echo "GOOS=$GOOS"
echo "GOARCH=$GOARCH"
echo "GOPATH=$GOPATH"

rm -rf $OUTPUT_DIR/*
rm -rf $GOPATH/pkg/*

stage_common
stage_scripts
compile_cell
compile_brain

rm -rf $GOPATH/pkg/*
rm -rf $GOPATH/bin/*
