#!/bin/bash

set -e

lattice_version=$(< /var/lattice/LATTICE_VERSION)
diego_version=$(< /var/lattice/DIEGO_VERSION)

echo "Installing Lattice ($lattice_version) (Diego $diego_version) - Brain"

lattice_brain_path=/tmp/lattice-build/brain

cp $lattice_brain_path/upstart/* /etc/init
cp $lattice_brain_path/bin/* /usr/local/bin
cp -a $lattice_brain_path/brain_health_check /var/lattice

mkdir -p /var/lattice/static-files

pushd $lattice_brain_path/bin > /dev/null
    tar czf /var/lattice/static-files/healthcheck.tgz healthcheck
    tar czf /var/lattice/static-files/lattice-cell-helpers.tgz builder launcher davtool
popd > /dev/null

mkdir -p /var/lattice/config
cp -a $lattice_brain_path/config /var/lattice

mkdir -p /var/lattice/setup
cp -a $lattice_brain_path/setup /var/lattice

mkdir -p /var/lattice/run
mkdir -p /var/lattice/log

touch /var/lattice/brain-ready

echo "Finished Installing Lattice Brain ($lattice_version) (Diego $diego_version)!"

