#!/bin/bash

set -e

mkdir -p /var/lattice/setup

LATTICE_COMMON_BUILD_PATH=/tmp/lattice-build/common

cp $LATTICE_COMMON_BUILD_PATH/health_check /var/lattice
cp $LATTICE_COMMON_BUILD_PATH/*_VERSION /var/lattice

cp $LATTICE_COMMON_BUILD_PATH/system-config/lattice.logrotate.txt /etc/logrotate.d/lattice
echo "## logrotation"  >> /etc/crontab
echo "*/5 * 	* * * 	root	/etc/cron.daily/logrotate" >> /etc/crontab

