#!/bin/bash

set -e

lattice_version=$(< /var/lattice/LATTICE_VERSION)

echo "Installing Lattice ($lattice_version) - Brain"

lattice_brain_path=/tmp/lattice-build/brain

cp $lattice_brain_path/upstart/* /etc/init
cp $lattice_brain_path/bin/* /usr/local/bin
cp -a $lattice_brain_path/brain_health_check /var/lattice 

mkdir -p /var/lattice/static-files

pushd $lattice_brain_path/bin > /dev/null
    tar czf /var/lattice/static-files/healthcheck.tgz healthcheck
    tar czf /var/lattice/static-files/lattice-support.tgz builder s3downloader s3uploader lrp-launcher
popd > /dev/null

mkdir -p /var/lattice/config
cp -a $lattice_brain_path/config /var/lattice

mkdir -p /var/lattice/setup
cp -a $lattice_brain_path/setup /var/lattice

mkdir -p /var/lattice/run
mkdir -p /var/lattice/log

start bootstrap &>> /var/lattice/log/brain-bootstrap.log

echo "Finished Installing Lattice Brain ($lattice_version)!"

