#!/bin/bash

set -e

mkdir -pv /var/lattice/setup

apt-get -y update
apt-get -y install curl

lattice_common_build_path=/tmp/lattice-build/common

cp -v $lattice_common_build_path/health_check /var/lattice

cp -v $lattice_common_build_path/LATTICE_VERSION /var/lattice

## log rotation ##
cp -v $lattice_common_build_path/system-config/lattice.logrotate.txt /etc/logrotate.d/lattice
echo "## logrotation"  >> /etc/crontab
echo "*/5 * 	* * * 	root	/etc/cron.daily/logrotate" >> /etc/crontab

