#!/bin/bash

set -e

lattice_version=$(< /var/lattice/LATTICE_VERSION)
diego_version=$(< /var/lattice/DIEGO_VERSION)

echo "Installing Lattice ($lattice_version) (Diego $diego_version) - Lattice Cell"

cell_build_path=/tmp/lattice-build/cell

#-n so we don't overwrite the brain upstart scripts in collocated installation.
#In collocated, Consul should run only in server mode and not use the cell consul upstart which is client-only mode
cp -n $cell_build_path/upstart/* /etc/init
cp -n $cell_build_path/bin/* /usr/local/bin
cp -a $cell_build_path/cell_health_check /var/lattice

mkdir -p /var/lattice/garden/depot
mkdir -p /var/lattice/garden/rootfs
mkdir -p /var/lattice/garden/overlays
mkdir -p /var/lattice/garden/graph

cp -a $cell_build_path/garden/garden-bin /var/lattice/garden/garden-bin
cp -a $cell_build_path/garden/skeleton /var/lattice/garden/skeleton

mkdir -p /var/lattice/config
cp -an $cell_build_path/config /var/lattice

mkdir -p /var/lattice/run
mkdir -p /var/lattice/log

touch /var/lattice/cell-ready

echo "Finished Installing Lattice Cell ($lattice_version) (Diego $diego_version)!"
