#!/bin/bash

set -e

COMPONENT_TO_INSTALL=$1

if [ $COMPONENT_TO_INSTALL != "diego-cell" ] && [ $COMPONENT_TO_INSTALL != "coordinator" ] && [ $COMPONENT_TO_INSTALL != "collocated" ]; then
    echo "Incorrect Usage. Must install either diego-cell or coordinator or both.
    Usage: install_from_tar diego-cell [LATTICE_TAR_PATH] OR
           install_from_tar coordinator [LATTICE_TAR_PATH]
           install_from_tar collocated [LATTICE_TAR_PATH]
    "
    exit 2
fi

tar -xf /tmp/lattice.tgz -C /tmp #File Provisioner puts it in /tmp/lattice.tgz

/tmp/lattice-build/common/install-common

if [ $COMPONENT_TO_INSTALL == "collocated" ]; then
    /tmp/lattice-build/coordinator/install-coordinator

    #Stop consul and bootstrap in collocated install so we can trigger dependencies to fire off the single bootstrap script
    #once the cell is installed too.
    stop consul
    stop bootstrap

    sleep 2

    /tmp/lattice-build/diego-cell/install-diego-cell
else
    /tmp/lattice-build/$COMPONENT_TO_INSTALL/install-$COMPONENT_TO_INSTALL
fi

