#!/bin/bash

setup_whetstone(){
    export GOPATH=$DIEGO_RELEASE_PATH

    rm -rf $GOPATH/pkg/*

    mkdir -p $GOPATH/src/github.com/pivotal-cf-experimental

    ln -sv $WORKSPACE_DIR/whetstone $GOPATH/src/github.com/pivotal-cf-experimental/whetstone
    ln -sv $WORKSPACE_DIR/lattice-cli $GOPATH/src/github.com/pivotal-cf-experimental/lattice-cli

    echo "=====================================>>>>>>getting ginkgo!!!"
    go get github.com/onsi/ginkgo/ginkgo
    echo "=====================================>>>>>>getting gomega!!!"
    go get github.com/onsi/gomega

    pushd $GOPATH/src/github.com/pivotal-cf-experimental/lattice-cli/ltc
    echo "go get in lattice-cli .=====================================>>>>>>lattice-cli!!!"
        go get -v .
    popd

    pushd $GOPATH/src/github.com/pivotal-cf-experimental/whetstone
    echo "go get in whetstone .=====================================>>>>>>whetstone!!!"
        go get -v .
    popd

    echo "gettin' gangsta =====================================>>>>>>!!!gangsta"
    rm -rfv $GOPATH/src/github.com/codegangsta/cli
    go get -v -u -t github.com/codegangsta/cli
}
