#!/bin/bash

setup_whetstone(){
    export GOPATH=$DIEGO_RELEASE_PATH
    export LATTICE_CLI_HOME=$WORKSPACE_DIR

    if [ -n "$GO_PIPELINE_NAME" ]; then #If we are running in CI, get the linux ltc binary from the build artifact.
        mkdir -pv $GOPATH/bin
        tar xvzf ltc.tar.gz -C $GOPATH/bin ltc-linux-amd64 && mv -v $GOPATH/bin/ltc-linux-amd64 $GOPATH/bin/ltc
    fi

    mkdir -pv $LATTICE_CLI_HOME/.lattice
    export PATH=$PATH:$GOPATH/bin
}
