#!/bin/bash

set -e

diego-edge/diego-edge-pipeline/helpers/run_with_docker \
 diego-edge/compile \
    /workspace/diego-edge-build \
    /workspace/diego-release \
    /workspace/cf-release \
    /workspace/diego-edge

rm -f diego-lite/diego-edge.tgz

tar -czf diego-edge.tgz diego-edge-build
