#!/bin/bash

set -e

pushd diego-release/loggregator
   git fetch
   git checkout origin/master
   git submodule update --init --recursive
popd

diego-edge/diego-edge-pipeline/helpers/run_with_docker \
 diego-edge/compile \
    /workspace/diego-edge \
    /workspace/diego-release \
    /workspace/cf-release \
    /workspace/diego-edge

rm -rf diego-edge.tgz
tar -czf diego-edge.tgz diego-edge
