#!/bin/bash

if [ -f "$LOCAL_LATTICE_TAR_PATH" ]; then
  echo "Found existing lattice tar at $LOCAL_LATTICE_TAR_PATH"
  echo "If you want to redownload lattice, delete the .lattice folder and try again."
else
  mkdir -p .lattice


  lattice_tar_version=$(cat $LATTICE_VERSION_FILE_PATH)

  if grep "-" $LATTICE_VERSION_FILE_PATH; then #it's unstable, released versions have hyphenless tag names as the git describe.
    lattice_download_url="https://s3-us-west-2.amazonaws.com/lattice/unstable/$lattice_tar_version/lattice.tgz"
  else
    lattice_download_url="https://s3-us-west-2.amazonaws.com/lattice/releases/$lattice_tar_version/lattice.tgz"
  fi

  echo "Downloading Lattice Release tar from $lattice_download_url => `pwd`/.lattice/lattice.tgz"
  wget --quiet $lattice_download_url -O .lattice/lattice.tgz
  echo "Download complete"
fi
