#!/bin/bash

export HOME=/home/vcap/app

unset GEM_PATH

if [ -d $HOME/.profile.d ]; then
        for i in $HOME/.profile.d/*.sh; do
                if [ -r $i ]; then
                        . $i
                fi
        done
        unset i
fi

DROPLET_BASE_DIR=$HOME
echo $$ >> $DROPLET_BASE_DIR/run.pid
exec bash -c "$*"
