#!/bin/bash

set -e

install_condenser() {
    mkdir -p /var/lattice/lighttpd/blobs /var/lattice/etc
    chown -R www-data:www-data /var/lattice/lighttpd

    /etc/init.d/lighttpd stop

    if [ -n "$LATTICE_USERNAME" ]; then
        cp /tmp/lattice-build/common/webdav/lighttpd.conf-auth-enabled /etc/lighttpd/lighttpd.conf
        echo $LATTICE_USERNAME:$(openssl passwd -crypt "$LATTICE_PASSWORD") > /var/lattice/etc/lighttpd.user
    else
        cp /tmp/lattice-build/common/webdav/lighttpd.conf-auth-disabled /etc/lighttpd/lighttpd.conf
    fi

    /etc/init.d/lighttpd start

    sleep 1
}

stage_cflinuxfs2_rootfs() {
    declare -r rootfs_download_path=~/download
    mkdir -p $rootfs_download_path
    wget https://github.com/cloudfoundry/stacks/releases/download/1.4.0/cflinuxfs2-1.4.0.tar.gz --quiet -O $rootfs_download_path/cflinuxfs2.tar.gz
    echo "Downloaded RootFS!"

    ## unpack to some fixed folder
    mkdir -p /var/lattice/rootfs/cflinuxfs2
    tar -xzf $rootfs_download_path/cflinuxfs2.tar.gz -C /var/lattice/rootfs/cflinuxfs2

    rm -f $rootfs_download_path/cflinuxfs2.tar.tgz
    echo "Preloaded CFLinuxFS2 RootFS enabled."

    sleep 1
}

COMPONENT_TO_INSTALL=$1

if [ $COMPONENT_TO_INSTALL != "cell" ] && [ $COMPONENT_TO_INSTALL != "brain" ] && [ $COMPONENT_TO_INSTALL != "collocated" ]; then
    echo "Incorrect Usage. Must install either cell or brain or both.
    Usage: install-from-tar cell [LATTICE_TAR_PATH] OR
           install-from-tar brain [LATTICE_TAR_PATH]
           install-from-tar collocated [LATTICE_TAR_PATH]
    "
    exit 2
fi

tar -xf /tmp/lattice.tgz -C /tmp

/tmp/lattice-build/scripts/install-common

export $(cat /var/lattice/setup/lattice-environment)

if [ $COMPONENT_TO_INSTALL == "collocated" ]; then
    /tmp/lattice-build/scripts/install-brain

    install_condenser
    stage_cflinuxfs2_rootfs

    /tmp/lattice-build/scripts/install-cell
elif [ $COMPONENT_TO_INSTALL == "brain" ]; then
    install_condenser

    /tmp/lattice-build/scripts/install-brain
elif [ $COMPONENT_TO_INSTALL == "cell" ]; then
    stage_cflinuxfs2_rootfs

    /tmp/lattice-build/scripts/install-cell
else
    exit 2
fi

start bootstrap

