#!/bin/bash
set -e

VAGRANT_BOX_NAME_OR_PATH=$1

pushd cf-release
    git submodule init -- src/gorouter
    git submodule update --recursive
popd

if [ -n "$1" ]; then
    VAGRANT_BOX_NAME_OR_PATH="ubuntu/trusty64"
fi

tar -xzf diego-final-release-created-by-ci.tgz
WORKSPACE_DIR_PATH=`pwd`

vagrant init $VAGRANT_BOX_NAME_OR_PATH --minimal --force
vagrant up --provider=virtualbox
vagrant ssh

    wget https://storage.googleapis.com/golang/go1.3.3.linux-amd64.tar.gz  -O - | sudo tar -xzf - -C /usr/local
    export PATH=$PATH:/usr/local/go/bin

    cd /vagrant
    ./diego-lite/scripts/compile "/vagrant/diego-release" "/vagrant/cf-release"

    sudo ./diego-lite/scripts/install

    sudo rm -rf /usr/local/go

    exit

vagrant package --output diego-lite.box
