#!/bin/bash
set -e

VAGRANT_BOX_NAME_OR_PATH=$1

if [ -z "$1" ]; then
    VAGRANT_BOX_NAME_OR_PATH="ubuntu/trusty64"
fi

if [ -z "$2" ]; then
    vboxmanage setproperty machinefolder $2/virtualbox_vms #/var/vcap/data/virtualbox_vms on gocd
    mkdir -p $2/vagrant_home
    export VAGRANT_HOME=$2/vagrant_home
fi

tar -xzf diego-final-release-created-by-ci.tgz
WORKSPACE_DIR_PATH=`pwd`

rm -f Vagrantfile
vagrant init $VAGRANT_BOX_NAME_OR_PATH --minimal
vagrant up --provider=virtualbox

vagrant ssh -c "wget https://storage.googleapis.com/golang/go1.3.3.linux-amd64.tar.gz  -O - | sudo tar -xzf - -C /usr/local"
vagrant ssh -c "PATH=$PATH:/usr/local/go/bin /vagrant/diego-lite/scripts/compile /vagrant/diego-release /vagrant/cf-release"
vagrant ssh -c "sudo PATH=$PATH:/usr/local/go/bin /vagrant/diego-lite/scripts/install"
vagrant ssh -c "sudo rm -rf /usr/local/go"

vagrant package --output diego-lite.box
