#!/bin/bash
set -e

export GOPATH=/workspace/diego-release
export PATH="$PATH:$GOPATH/bin"

echo "go getting cli dependencies..."
go get -v -t github.com/cloudfoundry-incubator/lattice/ltc/...
echo "gotten!"

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

echo "Running lattice-cli tests..."
$GOPATH/src/github.com/cloudfoundry-incubator/lattice/ltc/scripts/test
echo "Tests Passed!!!"

OUTDIR="/workspace/compiled-binaries"
mkdir -p $OUTDIR
export GOBIN="$OUTDIR"
rm -rf $GOPATH/pkg/*

pushd $GOPATH/src/github.com/cloudfoundry-incubator/lattice > /dev/null
    version_from_file=$(<LATTICE_VERSION)
popd > /dev/null

echo "Compiling cli ($version_from_file)..."

GOARCH=amd64 GOOS=linux go build \
    -ldflags "-X github.com/cloudfoundry-incubator/lattice/ltc/setup_cli.latticeVersion $version_from_file" \
    -o $OUTDIR/ltc-linux-amd64 \
    github.com/cloudfoundry-incubator/lattice/ltc

GOARCH=amd64 GOOS=darwin go build \
    -ldflags "-X github.com/cloudfoundry-incubator/lattice/ltc/setup_cli.latticeVersion $version_from_file" \
    -o $OUTDIR/ltc-darwin-amd64 \
    github.com/cloudfoundry-incubator/lattice/ltc

echo "generating ltc-checksum file"
pushd $GOPATH/src/github.com/cloudfoundry-incubator/lattice/ltc > /dev/null
    git rev-parse HEAD > $OUTDIR/ltc-checksum #TODO: Do we even use the ltc-checksum anymore?
popd > /dev/null

echo "Compilation Succeeded!!! Building tar..."

pushd $OUTDIR > /dev/null
    tar cvzf /workspace/ltc.tar.gz ltc*
popd > /dev/null
echo "tar built!"
