#!/bin/bash

set -e

if [[ ! -f $1 ]]; then
  echo "Usage:"
  echo -e "\t$0 /path/to/lattice.tgz"
  exit 1
fi

tar xzf "$1" --strip-components 1 --keep-directory-symlink --no-overwrite-dir --no-same-owner -C / -- cell
