#!/bin/bash

set -e

export $(cat /var/lattice/setup)

job_files=$(find /var/vcap/jobs/*/ -type f)
bosh_config=/var/vcap/bosh/settings.json
old_ip=$(cat /var/lattice/ip)
new_ip=$(ip route get 1 | awk '{print $NF;exit}')

perl -p -i -e "s/\\Q$old_ip\\E/$new_ip/g" $job_files
perl -p -i -e "s/placeholder-system-domain/$DOMAIN/g" $job_files
perl -p -i -e "s/placeholder-username/$USERNAME/g" $job_files
perl -p -i -e "s/placeholder-password/$PASSWORD/g" $job_files
perl -p -i -e "s/lattice-(cell|brain|collocated)-0/$HOST_ID/g" $job_files $bosh_config
