#!/bin/bash

set -e

export $(cat /var/lattice/setup)

# Replace placeholder / BOSH generated configuration

job_files=$(find /var/vcap/jobs/*/ -type f)
old_ip=$(cat /var/lattice/ip)
new_ip=$(ip route get 1 | awk '{print $NF;exit}')

perl -p -i -e "s/\\Q$old_ip\\E/$new_ip/g" $job_files
perl -p -i -e "s/placeholder\.system-domain/$DOMAIN/g" $job_files
perl -p -i -e "s/placeholder-username/$USERNAME/g" $job_files
perl -p -i -e "s/placeholder-password/$PASSWORD/g" $job_files
perl -p -i -e "s/lattice-(cell|brain|colocated)-0/$HOST_ID/g" $job_files

# Set hostname to provided host ID

bosh_config=/var/vcap/bosh/warden-cpi-agent-env.json
bosh_config_json=$(cat "$bosh_config")
echo $bosh_config_json | jq '. + {"agent_id": "'$HOST_ID'"}' > "$bosh_config"

rm -rf /var/vcap/store/*

