// This file was generated by counterfeiter
package fake_secure_client

import (
	"sync"

	"github.com/cloudfoundry-incubator/lattice/ltc/secure_shell"
)

type FakeSecureClient struct {
	NewSessionStub        func() (secure_shell.SecureSession, error)
	newSessionMutex       sync.RWMutex
	newSessionArgsForCall []struct{}
	newSessionReturns struct {
		result1 secure_shell.SecureSession
		result2 error
	}
}

func (fake *FakeSecureClient) NewSession() (secure_shell.SecureSession, error) {
	fake.newSessionMutex.Lock()
	fake.newSessionArgsForCall = append(fake.newSessionArgsForCall, struct{}{})
	fake.newSessionMutex.Unlock()
	if fake.NewSessionStub != nil {
		return fake.NewSessionStub()
	} else {
		return fake.newSessionReturns.result1, fake.newSessionReturns.result2
	}
}

func (fake *FakeSecureClient) NewSessionCallCount() int {
	fake.newSessionMutex.RLock()
	defer fake.newSessionMutex.RUnlock()
	return len(fake.newSessionArgsForCall)
}

func (fake *FakeSecureClient) NewSessionReturns(result1 secure_shell.SecureSession, result2 error) {
	fake.NewSessionStub = nil
	fake.newSessionReturns = struct {
		result1 secure_shell.SecureSession
		result2 error
	}{result1, result2}
}

var _ secure_shell.SecureClient = new(FakeSecureClient)
