#!/bin/bash

set -e

docker pull ubuntu:trusty
docker build --force-rm --no-cache -t $DOCKER_IMAGE lattice/lattice-dependencies-pipeline/02_publish_pipeline_docker_image/pipeline_image/
docker push $DOCKER_IMAGE

#Also publish to Dockerhub. Lattice is open source!
docker login --email="$DOCKER_HUB_EMAIL"  --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
docker build --force-rm --no-cache -t cloudfoundry/lattice-pipeline lattice/lattice-dependencies-pipeline/02_publish_pipeline_docker_image/pipeline_image/
docker push cloudfoundry/lattice-pipeline
