#!/bin/bash
set -e

save_logs() {
    echo "save logs"

    pushd $WORKSPACE_DIR/diego-release/src/github.com/cloudfoundry-incubator/lattice
        vagrant ssh -c "sudo tar -czf /vagrant/vagrant_upstart_logs.tgz /var/log/upstart /var/lattice/log"
    popd

    mv lattice/vagrant_upstart_logs.tgz .
}

cleanup_vagrant() {
    echo "cleaning up vagrant"
    pushd $WORKSPACE_DIR/diego-release/src/github.com/cloudfoundry-incubator/lattice
        vagrant destroy --force
    popd
}

cleanup(){
    set +e
    save_logs
    cleanup_vagrant
}

start_lattice_vagrant(){
    cp $LATTICE_TAR_PATH lattice
    pushd $WORKSPACE_DIR/diego-release/src/github.com/cloudfoundry-incubator/lattice
        vagrant up --provider=virtualbox
        export $(cat .lattice-environment)
    popd
}

assert_that_vtx_is_enabled_if_linux(){
    if [ -a /proc/cpuinfo ]; then
        set +e
        egrep "vmx|svm" /proc/cpuinfo

        if [ "$?" -ne "0" ]; then
            echo "VT-x is not enabled on this machine."
            exit 2
        fi
        
        set -e
    fi
}

assert_that_vtx_is_enabled_if_linux

export DIEGO_RELEASE_PATH=$1
export LATTICE_TAR_PATH=$2
export VAGRANT_LATTICE_TAR_PATH=/vagrant/$(basename $LATTICE_TAR_PATH)
WORKSPACE_DIR=`pwd`

trap cleanup EXIT

start_lattice_vagrant

source $(dirname $0)/helpers/setup_whetstone
setup_whetstone

pushd $WORKSPACE_DIR/diego-release/src/github.com/cloudfoundry-incubator/lattice
    blob_access_key=$(vagrant ssh -c 'egrep "^admin\.key=" /etc/riak-cs/riak-cs.conf' 2> /dev/null | grep '^admin.key=' | sed 's/^admin.key=//')
    blob_secret_key=$(vagrant ssh -c 'egrep "^admin\.secret=" /etc/riak-cs/riak-cs.conf' 2> /dev/null | grep '^admin.secret=' | sed 's/^admin.secret=//')
popd

printf "{\"target\":\"%s\",\"blob_target_info\":{\"host\":\"%s\",\"port\":%d,\"access_key\":\"%s\",\"secret_key\":\"%s\",\"bucket_name\":\"%s\"}}" \
    "$SYSTEM_DOMAIN" \
    "$SYSTEM_IP" \
    8980 \
    "${blob_access_key%%[[:space:]]}" \
    "${blob_secret_key%%[[:space:]]}" \
    "condenser-bucket" | json_pp \
    > $LATTICE_CLI_HOME/.lattice/config.json
sync

ltc test -v --timeout=5m

