#!/bin/bash
set -e

print_provider_specific_terraform_configuration(){
    if [ "$1" == "--without-outputs" ]; then
        terraform_outputs=""
    else
        terraform_outputs=',
        "output": {
                    "lattice_target": {
                        "value": "${module.lattice-aws.lattice_target}"
                    },
                    "lattice_username": {
                        "value": "${module.lattice-aws.lattice_username}"
                    },
                    "lattice_password": {
                        "value": "${module.lattice-aws.lattice_password}"
                    }
        }'
    fi

    printf '{
                "module":{
                    "lattice-aws":{
                        "source":"%s",
                        "lattice_username": "user",
                        "lattice_password": "pass",
                        "local_lattice_tar_path": "%s",
                        "num_cells": "1",
                        "aws_access_key": "%s",
                        "aws_secret_key": "%s",
                        "aws_region": "us-west-1",
                        "aws_key_name": "ec2-west-1",
                        "aws_ssh_private_key_file": "%s/ec2-west-1.pem"
                    }
                }%s
            }' \
            "$LATTICE_DIR/terraform/aws" \
            "$LATTICE_TAR_PATH" \
            "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" "$TF_WORKING_DIR" \
            "$terraform_outputs"
}

download_provider_specific_credentials(){
    aws s3 cp s3://lattice-gocd/credentials/ec2-west-1.pem $TF_WORKING_DIR/ec2-west-1.pem
    chmod 600 $TF_WORKING_DIR/ec2-west-1.pem
}
export LATTICE_DIR=$(cd `dirname $0` && cd ../.. && pwd)/

source $(dirname $0)/helpers/run_terraform_whetstone
