#!/bin/bash
set -e

print_provider_specific_terraform_configuration(){
    if [ "$1" == "--without-outputs" ]; then
        terraform_outputs=""
    else
        terraform_outputs=',
        "output": {
                    "lattice_target": {
                        "value": "${module.lattice-google.lattice_target}"
                    },
                    "lattice_username": {
                        "value": "${module.lattice-google.lattice_username}"
                    },
                    "lattice_password": {
                        "value": "${module.lattice-google.lattice_password}"
                    }
        }'
    fi

    printf '{
                "module":{
                    "lattice-google":{
                        "source":"%s",
                        "lattice_username": "user",
                        "lattice_password": "pass",
                        "local_lattice_tar_path": "%s",
                        "gce_account_file": "%s",
                        "gce_project": "%s",
                        "gce_ssh_private_key_file": "%s",
                        "gce_ssh_user": "pivotal"
                    }
                }%s
            }
            ' \
            "$LATTICE_DIR/terraform/google" \
            "$LATTICE_TAR_PATH" \
            "$TF_WORKING_DIR/gce-account.json" \
            "$(cat $TF_WORKING_DIR/gce-project)" \
            "$TF_WORKING_DIR/gce-ssh-key" \
            "$terraform_outputs"
}

download_provider_specific_credentials(){
    aws s3 cp s3://lattice-gocd/credentials/gce-credentials.tar - | tar -xf - -C $TF_WORKING_DIR
    chmod 600 $TF_WORKING_DIR/gce-ssh-key
}
export LATTICE_DIR=$(cd `dirname $0` && cd ../.. && pwd)/

source $(dirname $0)/helpers/run_terraform_whetstone
