#!/bin/bash
set -e

save_logs() {
    echo "save logs"

    pushd $LATTICE_DIR
        vagrant ssh -c "sudo tar -czf /vagrant/build/vagrant_upstart_logs.tgz /var/log/upstart /var/lattice/log"
    popd
}

cleanup_vagrant() {
    echo "cleaning up vagrant"
    pushd $LATTICE_DIR
        vagrant destroy --force
    popd
}

cleanup(){
    set +e
    save_logs
    cleanup_vagrant
}

start_lattice_vagrant(){
    pushd $LATTICE_DIR
        vagrant up --provider=virtualbox
        export $(cat .lattice-environment)
    popd
}

assert_that_vtx_is_enabled_if_linux(){
    if [ -a /proc/cpuinfo ]; then
        set +e
        egrep "vmx|svm" /proc/cpuinfo

        if [ "$?" -ne "0" ]; then
            echo "VT-x is not enabled on this machine."
            exit 2
        fi
        
        set -e
    fi
}

assert_that_vtx_is_enabled_if_linux

export VAGRANT_LATTICE_TAR_PATH=/vagrant/build/lattice.tgz
LATTICE_DIR=$(cd `dirname $0` && cd ../.. && pwd)/

trap cleanup EXIT

start_lattice_vagrant

source $LATTICE_DIR/pipeline/02_test/helpers/setup_whetstone
setup_whetstone

pushd $LATTICE_DIR
    blob_access_key=$(vagrant ssh -c 'egrep "^admin\.key=" /etc/riak-cs/riak-cs.conf' 2> /dev/null | grep '^admin.key=' | sed 's/^admin.key=//')
    blob_secret_key=$(vagrant ssh -c 'egrep "^admin\.secret=" /etc/riak-cs/riak-cs.conf' 2> /dev/null | grep '^admin.secret=' | sed 's/^admin.secret=//')
popd

printf "{\"target\":\"%s\",\"blob_target_info\":{\"host\":\"%s\",\"port\":%d,\"access_key\":\"%s\",\"secret_key\":\"%s\",\"bucket_name\":\"%s\"}}" \
    "$SYSTEM_DOMAIN" \
    "$SYSTEM_IP" \
    8980 \
    "${blob_access_key%%[[:space:]]}" \
    "${blob_secret_key%%[[:space:]]}" \
    "condenser-bucket" | json_pp \
    > $LATTICE_CLI_HOME/.lattice/config.json
sync

ltc -v
ltc test -v --timeout=5m

