#!/bin/bash
set -e

print_provider_specific_terraform_configuration(){
    if [ "$1" == "--without-outputs" ]; then
        terraform_outputs=""
    else
        terraform_outputs=',
        "output": {
                    "lattice_target": {
                        "value": "${module.lattice-digitalocean.lattice_target}"
                    },
                    "lattice_username": {
                        "value": "${module.lattice-digitalocean.lattice_username}"
                    },
                    "lattice_password": {
                        "value": "${module.lattice-digitalocean.lattice_password}"
                    }
        }'
    fi

    printf '{
                "module":{
                    "lattice-digitalocean":{
                        "source":"%s",
                        "local_lattice_tar_path": "%s",
                        "num_cells": "1",
                        "do_token": "%s",
                        "do_ssh_private_key_file": "%s",
                        "do_ssh_public_key_id": "%s",
                        "do_region": "nyc3"
                    }
                }%s
            }' \
            "$LATTICE_DIR/terraform/digitalocean" \
            "$LATTICE_TAR_PATH" \
            "$(cat $TF_WORKING_DIR/lattice-ci-digitalocean-api-token)" \
            "$TF_WORKING_DIR/lattice-ci-digitalocean.pem" \
            "$(cat $TF_WORKING_DIR/lattice-ci-digitalocean-ssh-key-id)" \
            "$terraform_outputs"
}

download_provider_specific_credentials(){
    tar -xf /run/build/do-credentials.tar -C $TF_WORKING_DIR 
}

source $(dirname $0)/helpers/run_terraform_whetstone
