#!/bin/bash
set -e

source $(dirname $0)/../helpers/build_ltc_helpers

setup_go_env

construct_ltc_gopath

run_unit_tests

git_describe_lattice
git_describe_diego

go_build_ltc

generate_ltc_tarball $LATTICE_SRC_PATH/build
