// This file was generated by counterfeiter
package fake_blob_store

import (
	"io"
	"sync"

	"github.com/cloudfoundry-incubator/bbs/models"
	"github.com/cloudfoundry-incubator/lattice/ltc/blob_store/blob"
	"github.com/cloudfoundry-incubator/lattice/ltc/droplet_runner"
)

type FakeBlobStore struct {
	ListStub        func() ([]blob.Blob, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct{}
	listReturns     struct {
		result1 []blob.Blob
		result2 error
	}
	DeleteStub        func(path string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		path string
	}
	deleteReturns struct {
		result1 error
	}
	UploadStub        func(path string, contents io.ReadSeeker) error
	uploadMutex       sync.RWMutex
	uploadArgsForCall []struct {
		path     string
		contents io.ReadSeeker
	}
	uploadReturns struct {
		result1 error
	}
	DownloadStub        func(path string) (io.ReadCloser, error)
	downloadMutex       sync.RWMutex
	downloadArgsForCall []struct {
		path string
	}
	downloadReturns struct {
		result1 io.ReadCloser
		result2 error
	}
	DownloadAppBitsActionStub        func(dropletName string) *models.Action
	downloadAppBitsActionMutex       sync.RWMutex
	downloadAppBitsActionArgsForCall []struct {
		dropletName string
	}
	downloadAppBitsActionReturns struct {
		result1 *models.Action
	}
	DeleteAppBitsActionStub        func(dropletName string) *models.Action
	deleteAppBitsActionMutex       sync.RWMutex
	deleteAppBitsActionArgsForCall []struct {
		dropletName string
	}
	deleteAppBitsActionReturns struct {
		result1 *models.Action
	}
	UploadDropletActionStub        func(dropletName string) *models.Action
	uploadDropletActionMutex       sync.RWMutex
	uploadDropletActionArgsForCall []struct {
		dropletName string
	}
	uploadDropletActionReturns struct {
		result1 *models.Action
	}
	UploadDropletMetadataActionStub        func(dropletName string) *models.Action
	uploadDropletMetadataActionMutex       sync.RWMutex
	uploadDropletMetadataActionArgsForCall []struct {
		dropletName string
	}
	uploadDropletMetadataActionReturns struct {
		result1 *models.Action
	}
	DownloadDropletActionStub        func(dropletName string) *models.Action
	downloadDropletActionMutex       sync.RWMutex
	downloadDropletActionArgsForCall []struct {
		dropletName string
	}
	downloadDropletActionReturns struct {
		result1 *models.Action
	}
}

func (fake *FakeBlobStore) List() ([]blob.Blob, error) {
	fake.listMutex.Lock()
	fake.listArgsForCall = append(fake.listArgsForCall, struct{}{})
	fake.listMutex.Unlock()
	if fake.ListStub != nil {
		return fake.ListStub()
	} else {
		return fake.listReturns.result1, fake.listReturns.result2
	}
}

func (fake *FakeBlobStore) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeBlobStore) ListReturns(result1 []blob.Blob, result2 error) {
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []blob.Blob
		result2 error
	}{result1, result2}
}

func (fake *FakeBlobStore) Delete(path string) error {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		path string
	}{path})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(path)
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *FakeBlobStore) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeBlobStore) DeleteArgsForCall(i int) string {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].path
}

func (fake *FakeBlobStore) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBlobStore) Upload(path string, contents io.ReadSeeker) error {
	fake.uploadMutex.Lock()
	fake.uploadArgsForCall = append(fake.uploadArgsForCall, struct {
		path     string
		contents io.ReadSeeker
	}{path, contents})
	fake.uploadMutex.Unlock()
	if fake.UploadStub != nil {
		return fake.UploadStub(path, contents)
	} else {
		return fake.uploadReturns.result1
	}
}

func (fake *FakeBlobStore) UploadCallCount() int {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return len(fake.uploadArgsForCall)
}

func (fake *FakeBlobStore) UploadArgsForCall(i int) (string, io.ReadSeeker) {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return fake.uploadArgsForCall[i].path, fake.uploadArgsForCall[i].contents
}

func (fake *FakeBlobStore) UploadReturns(result1 error) {
	fake.UploadStub = nil
	fake.uploadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBlobStore) Download(path string) (io.ReadCloser, error) {
	fake.downloadMutex.Lock()
	fake.downloadArgsForCall = append(fake.downloadArgsForCall, struct {
		path string
	}{path})
	fake.downloadMutex.Unlock()
	if fake.DownloadStub != nil {
		return fake.DownloadStub(path)
	} else {
		return fake.downloadReturns.result1, fake.downloadReturns.result2
	}
}

func (fake *FakeBlobStore) DownloadCallCount() int {
	fake.downloadMutex.RLock()
	defer fake.downloadMutex.RUnlock()
	return len(fake.downloadArgsForCall)
}

func (fake *FakeBlobStore) DownloadArgsForCall(i int) string {
	fake.downloadMutex.RLock()
	defer fake.downloadMutex.RUnlock()
	return fake.downloadArgsForCall[i].path
}

func (fake *FakeBlobStore) DownloadReturns(result1 io.ReadCloser, result2 error) {
	fake.DownloadStub = nil
	fake.downloadReturns = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeBlobStore) DownloadAppBitsAction(dropletName string) *models.Action {
	fake.downloadAppBitsActionMutex.Lock()
	fake.downloadAppBitsActionArgsForCall = append(fake.downloadAppBitsActionArgsForCall, struct {
		dropletName string
	}{dropletName})
	fake.downloadAppBitsActionMutex.Unlock()
	if fake.DownloadAppBitsActionStub != nil {
		return fake.DownloadAppBitsActionStub(dropletName)
	} else {
		return fake.downloadAppBitsActionReturns.result1
	}
}

func (fake *FakeBlobStore) DownloadAppBitsActionCallCount() int {
	fake.downloadAppBitsActionMutex.RLock()
	defer fake.downloadAppBitsActionMutex.RUnlock()
	return len(fake.downloadAppBitsActionArgsForCall)
}

func (fake *FakeBlobStore) DownloadAppBitsActionArgsForCall(i int) string {
	fake.downloadAppBitsActionMutex.RLock()
	defer fake.downloadAppBitsActionMutex.RUnlock()
	return fake.downloadAppBitsActionArgsForCall[i].dropletName
}

func (fake *FakeBlobStore) DownloadAppBitsActionReturns(result1 *models.Action) {
	fake.DownloadAppBitsActionStub = nil
	fake.downloadAppBitsActionReturns = struct {
		result1 *models.Action
	}{result1}
}

func (fake *FakeBlobStore) DeleteAppBitsAction(dropletName string) *models.Action {
	fake.deleteAppBitsActionMutex.Lock()
	fake.deleteAppBitsActionArgsForCall = append(fake.deleteAppBitsActionArgsForCall, struct {
		dropletName string
	}{dropletName})
	fake.deleteAppBitsActionMutex.Unlock()
	if fake.DeleteAppBitsActionStub != nil {
		return fake.DeleteAppBitsActionStub(dropletName)
	} else {
		return fake.deleteAppBitsActionReturns.result1
	}
}

func (fake *FakeBlobStore) DeleteAppBitsActionCallCount() int {
	fake.deleteAppBitsActionMutex.RLock()
	defer fake.deleteAppBitsActionMutex.RUnlock()
	return len(fake.deleteAppBitsActionArgsForCall)
}

func (fake *FakeBlobStore) DeleteAppBitsActionArgsForCall(i int) string {
	fake.deleteAppBitsActionMutex.RLock()
	defer fake.deleteAppBitsActionMutex.RUnlock()
	return fake.deleteAppBitsActionArgsForCall[i].dropletName
}

func (fake *FakeBlobStore) DeleteAppBitsActionReturns(result1 *models.Action) {
	fake.DeleteAppBitsActionStub = nil
	fake.deleteAppBitsActionReturns = struct {
		result1 *models.Action
	}{result1}
}

func (fake *FakeBlobStore) UploadDropletAction(dropletName string) *models.Action {
	fake.uploadDropletActionMutex.Lock()
	fake.uploadDropletActionArgsForCall = append(fake.uploadDropletActionArgsForCall, struct {
		dropletName string
	}{dropletName})
	fake.uploadDropletActionMutex.Unlock()
	if fake.UploadDropletActionStub != nil {
		return fake.UploadDropletActionStub(dropletName)
	} else {
		return fake.uploadDropletActionReturns.result1
	}
}

func (fake *FakeBlobStore) UploadDropletActionCallCount() int {
	fake.uploadDropletActionMutex.RLock()
	defer fake.uploadDropletActionMutex.RUnlock()
	return len(fake.uploadDropletActionArgsForCall)
}

func (fake *FakeBlobStore) UploadDropletActionArgsForCall(i int) string {
	fake.uploadDropletActionMutex.RLock()
	defer fake.uploadDropletActionMutex.RUnlock()
	return fake.uploadDropletActionArgsForCall[i].dropletName
}

func (fake *FakeBlobStore) UploadDropletActionReturns(result1 *models.Action) {
	fake.UploadDropletActionStub = nil
	fake.uploadDropletActionReturns = struct {
		result1 *models.Action
	}{result1}
}

func (fake *FakeBlobStore) UploadDropletMetadataAction(dropletName string) *models.Action {
	fake.uploadDropletMetadataActionMutex.Lock()
	fake.uploadDropletMetadataActionArgsForCall = append(fake.uploadDropletMetadataActionArgsForCall, struct {
		dropletName string
	}{dropletName})
	fake.uploadDropletMetadataActionMutex.Unlock()
	if fake.UploadDropletMetadataActionStub != nil {
		return fake.UploadDropletMetadataActionStub(dropletName)
	} else {
		return fake.uploadDropletMetadataActionReturns.result1
	}
}

func (fake *FakeBlobStore) UploadDropletMetadataActionCallCount() int {
	fake.uploadDropletMetadataActionMutex.RLock()
	defer fake.uploadDropletMetadataActionMutex.RUnlock()
	return len(fake.uploadDropletMetadataActionArgsForCall)
}

func (fake *FakeBlobStore) UploadDropletMetadataActionArgsForCall(i int) string {
	fake.uploadDropletMetadataActionMutex.RLock()
	defer fake.uploadDropletMetadataActionMutex.RUnlock()
	return fake.uploadDropletMetadataActionArgsForCall[i].dropletName
}

func (fake *FakeBlobStore) UploadDropletMetadataActionReturns(result1 *models.Action) {
	fake.UploadDropletMetadataActionStub = nil
	fake.uploadDropletMetadataActionReturns = struct {
		result1 *models.Action
	}{result1}
}

func (fake *FakeBlobStore) DownloadDropletAction(dropletName string) *models.Action {
	fake.downloadDropletActionMutex.Lock()
	fake.downloadDropletActionArgsForCall = append(fake.downloadDropletActionArgsForCall, struct {
		dropletName string
	}{dropletName})
	fake.downloadDropletActionMutex.Unlock()
	if fake.DownloadDropletActionStub != nil {
		return fake.DownloadDropletActionStub(dropletName)
	} else {
		return fake.downloadDropletActionReturns.result1
	}
}

func (fake *FakeBlobStore) DownloadDropletActionCallCount() int {
	fake.downloadDropletActionMutex.RLock()
	defer fake.downloadDropletActionMutex.RUnlock()
	return len(fake.downloadDropletActionArgsForCall)
}

func (fake *FakeBlobStore) DownloadDropletActionArgsForCall(i int) string {
	fake.downloadDropletActionMutex.RLock()
	defer fake.downloadDropletActionMutex.RUnlock()
	return fake.downloadDropletActionArgsForCall[i].dropletName
}

func (fake *FakeBlobStore) DownloadDropletActionReturns(result1 *models.Action) {
	fake.DownloadDropletActionStub = nil
	fake.downloadDropletActionReturns = struct {
		result1 *models.Action
	}{result1}
}

var _ droplet_runner.BlobStore = new(FakeBlobStore)
