#!/bin/bash

set -e

lattice_version=$(< /var/lattice/LATTICE_VERSION)

echo "Installing Lattice ($lattice_version) - Coordinator"

lattice_coordinator_path=/tmp/lattice-build/coordinator

cp -v $lattice_coordinator_path/upstart/* /etc/init
cp -v $lattice_coordinator_path/bin/* /usr/local/bin
cp -av $lattice_coordinator_path/coordinator_health_check /var/lattice 

mkdir -pv /var/lattice/static-files

pushd $lattice_coordinator_path/bin > /dev/null
    tar -cvzf /var/lattice/static-files/healthcheck.tgz healthcheck
popd > /dev/null

mkdir -pv /var/lattice/config
cp -av $lattice_coordinator_path/config /var/lattice

mkdir -pv /var/lattice/setup
cp -av $lattice_coordinator_path/setup /var/lattice

mkdir -pv /var/lattice/run
mkdir -pv /var/lattice/log

start bootstrap &>> /var/lattice/log/coordinator-bootstrap.log

echo "Finished Installing Lattice Coordinator ($lattice_version)!"

