#!/bin/bash

set -e

echo "Installing Lattice - Coordinator"

lattice_coordinator_path=/tmp/lattice-build/coordinator

cp -v $lattice_coordinator_path/upstart/* /etc/init
cp -v $lattice_coordinator_path/bin/* /usr/local/bin
cp -av $lattice_coordinator_path/coordinator_health_check /var/lattice 

mkdir -pv /var/lattice/static-files/docker-circus

pushd $lattice_coordinator_path/bin > /dev/null
    tar -czf /var/lattice/static-files/docker-circus/docker-circus.tgz spy
popd > /dev/null

mkdir -pv /var/lattice/config
cp -av $lattice_coordinator_path/config /var/lattice

mkdir -pv /var/lattice/setup
cp -av $lattice_coordinator_path/setup /var/lattice

mkdir -pv /var/lattice/run
mkdir -pv /var/lattice/log

start bootstrap &>> /var/lattice/log/coordinator-bootstrap.log

export $(cat /var/lattice/setup/lattice-environment)

echo "Finished!
Lattice is now installed and running. You may target it with the Lattice cli via:
ltc target $SYSTEM_DOMAIN"

