#!/bin/bash
expected_processes=( "$@" )
expected_num_processes=${#expected_processes[@]}
num_running_processes=0
for process in "${expected_processes[@]}";
do
    instances_of_current_process=$(ps uawx | cut -c66- | egrep "^$process" | grep -v egrep | wc -l )
    if [ "$instances_of_current_process" == "1" ]; then
        echo "$process: Running"
    elif [ "$instances_of_current_process" -gt "1" ]; then
        echo "$process: more than one was running - expected 1, got $instances_of_current_process"
    else
        echo "$process: *DOWN*"
    fi

    num_running_processes=$(($num_running_processes + $instances_of_current_process))
done


if [ $num_running_processes -ne "$expected_num_processes" ]; then
    echo "expected $expected_num_processes processes to be running, but got $num_running_processes"
    exit 1
else
    echo "$num_running_processes/$expected_num_processes processes up and running. yay!"
fi
