#!/bin/bash

set -e

if [[ -z $1 ]] && [[ -t 1 ]]; then
    echo "Usage:"
    echo -e "\t$0 /path/to/lattice.tgz [lattice release version]"
    echo -e "\t$0 [lattice release version] > /path/to/lattice.tgz"
    exit 1
fi

if [[ -t 1 ]]; then
  lattice_tgz=$1
  version_override=$2
else
  lattice_tgz="-"
  version_override=$1
fi

lattice_release_dir=$(cd `dirname $0` && cd .. && pwd)
diego_release_dir=$lattice_release_dir/diego-release
lattice_dir=$lattice_release_dir/src/github.com/cloudfoundry-incubator/lattice
receptor_dir=$lattice_release_dir/src/github.com/cloudfoundry-incubator/receptor

lattice_release_version=${version_override:-`git -C "$lattice_release_dir" describe --tags --always`}
lattice_version=$(git -C "$lattice_dir" describe --tags --always)
receptor_version=$(git -C "$receptor_dir" describe --tags --always)

tmp_dir=$(mktemp -d /tmp/lattice.XXXXXX)

cp -a $lattice_release_dir/release/install $tmp_dir/

export GOPATH=$lattice_release_dir:$diego_release_dir
export GOOS=linux
export GOARCH=amd64

# Brain

cp -a $lattice_release_dir/release/brain $tmp_dir/

brain_bin_dir=$tmp_dir/brain/usr/local/bin
brain_lighttpd_dir=$tmp_dir/brain/var/lattice/lighttpd
brain_cell_helper_dir=$tmp_dir/brain/var/vcap/jobs/file_server/packages/cell-helpers
brain_versions_dir=$tmp_dir/brain/var/lattice/versions
mkdir -p $brain_lighttpd_dir $brain_bin_dir $brain_cell_helper_dir $brain_versions_dir

go build -a -o $brain_lighttpd_dir/linux/ltc github.com/cloudfoundry-incubator/lattice/ltc
GOOS=darwin go build -a -o $brain_lighttpd_dir/osx/ltc github.com/cloudfoundry-incubator/lattice/ltc
go build -a -o $brain_bin_dir/receptor github.com/cloudfoundry-incubator/receptor/cmd/receptor

pushd $brain_cell_helper_dir >/dev/null
  go build -a github.com/cloudfoundry-incubator/lattice/cell-helpers/davtool
  go build -a github.com/cloudfoundry-incubator/lattice/cell-helpers/s3tool
  tar czf cell-helpers.tgz davtool s3tool
  rm -f davtool s3tool
popd >/dev/null

echo $lattice_version > $brain_versions_dir/LATTICE
echo $lattice_release_version > $brain_versions_dir/LATTICE_RELEASE
echo $receptor_version > $brain_versions_dir/RECEPTOR

# Cell

cell_bin_dir=$tmp_dir/cell/usr/local/bin
cell_versions_dir=$tmp_dir/cell/var/lattice/versions
mkdir -p $cell_bin_dir $cell_versions_dir

go build -a -o $cell_bin_dir/tee2metron github.com/cloudfoundry-incubator/lattice/cell-helpers/tee2metron

echo $lattice_version > $cell_versions_dir/LATTICE
echo $lattice_release_version > $cell_versions_dir/LATTICE_RELEASE

# Output

tar -czf "$lattice_tgz" -C "$tmp_dir" brain cell install

rm -rf "$tmp_dir"
