#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "Incorrect Usage. Usage: $0 /path/to/lattice.tgz [lattice release version]"
    exit 1
fi

LATTICE_TGZ=$1

LATTICE_RELEASE_DIR=$(cd `dirname $0` && cd .. && pwd)
DIEGO_RELEASE_DIR=$LATTICE_RELEASE_DIR/diego-release
LATTICE_DIR=$LATTICE_RELEASE_DIR/src/github.com/cloudfoundry-incubator/lattice
RECEPTOR_DIR=$LATTICE_RELEASE_DIR/src/github.com/cloudfoundry-incubator/receptor

LATTICE_RELEASE_VERSION=${2:-`git -C "$LATTICE_RELEASE_DIR" describe --tags --always`}
LATTICE_VERSION=$(git -C "$LATTICE_DIR" describe --tags --always)
RECEPTOR_VERSION=$(git -C "$RECEPTOR_DIR" describe --tags --always)

TMP_DIR=$(mktemp -d /tmp/lattice.XXXXXX)

cp -a $LATTICE_RELEASE_DIR/release/root $TMP_DIR/
cp $LATTICE_RELEASE_DIR/release/src/install $TMP_DIR/

VERSIONS_DIR=$TMP_DIR/root/var/lattice/versions
BIN_DIR=$TMP_DIR/root/usr/local/bin
CELL_HELPER_DIR=$TMP_DIR/root/var/vcap/jobs/file_server/packages/cell-helpers

mkdir -p $VERSIONS_DIR $BIN_DIR $CELL_HELPER_DIR

export GOOS=linux
export GOARCH=amd64
export GOPATH=$LATTICE_RELEASE_DIR:$DIEGO_RELEASE_DIR

pushd $BIN_DIR
    go build -a github.com/cloudfoundry-incubator/receptor/cmd/receptor
popd

pushd $CELL_HELPER_DIR
    go build -a github.com/cloudfoundry-incubator/lattice/cell-helpers/davtool
    go build -a github.com/cloudfoundry-incubator/lattice/cell-helpers/s3tool
    tar czf cell-helpers.tgz davtool s3tool
    rm -f davtool s3tool
popd

echo $LATTICE_RELEASE_VERSION > $VERSIONS_DIR/LATTICE_RELEASE
echo $LATTICE_VERSION > $VERSIONS_DIR/LATTICE
echo $RECEPTOR_VERSION > $VERSIONS_DIR/RECEPTOR

tar czf "$1" -C $TMP_DIR .

rm -rf $TMP_DIR
