#!/bin/bash
set -e

export GOPATH=/workspace/diego-release
export PATH="$PATH:$GOPATH/bin"
mkdir -p $GOPATH/src/github.com/cloudfoundry-incubator/lattice
echo "$(cp -rv lattice/cli $GOPATH/src/github.com/cloudfoundry-incubator/lattice)" #so that we can run locally without clobbering our lattice-cli repo

echo "go getting cli dependencies..."
go get -v -t github.com/cloudfoundry-incubator/lattice/cli/...
echo "gotten!"

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

echo "Running lattice-cli tests..."
$GOPATH/src/github.com/cloudfoundry-incubator/lattice/cli/scripts/test
echo "Tests Passed!!!"

OUTDIR="/workspace/compiled-binaries"
mkdir -p $OUTDIR
export GOBIN="$OUTDIR"
rm -rf $GOPATH/pkg/*

echo "Compiling cli..."
GOARCH=amd64 GOOS=linux go build -o $OUTDIR/ltc-linux-amd64 github.com/cloudfoundry-incubator/lattice/cli/ltc
GOARCH=amd64 GOOS=darwin go build -o $OUTDIR/ltc-darwin-amd64 github.com/cloudfoundry-incubator/lattice/cli/ltc

echo "generating ltc-checksum file"
pushd $GOPATH/src/github.com/cloudfoundry-incubator/lattice/cli > /dev/null
    git rev-parse HEAD > $OUTDIR/ltc-checksum #TODO: Do we even use the ltc-checksum anymore?
popd > /dev/null

echo "Compilation Succeeded!!! Building tar..."

pushd $OUTDIR > /dev/null
    tar cvzf /workspace/ltc.tar.gz ltc*
popd > /dev/null
echo "tar built!"
