#!/bin/bash

set -e

export CI_DIR=`mktemp -d $HOME/.lattice-ci.XXXXXX`

LATTICE_DIR=$(cd `dirname $0` && cd ../../.. && pwd)
source $LATTICE_DIR/pipeline/local/env

## default gocd material dependency behavior
pushd $CI_DIR
	git clone git@github.com:cloudfoundry-incubator/lattice -b pipeline 
	git clone git@github.com:cloudfoundry-incubator/diego-release -b master
	pushd diego-release
		git reset $GO_REVISION_DIEGO_RELEASE --hard
		git submodule update --init --recursive
	popd

	git clone git@github.com:cloudfoundry/cf-release -b runtime-passed 
	pushd cf-release
		git reset $GO_REVISION_CF_RELEASE --hard
		git submodule update --init --recursive
	popd
popd

## custom steps in gocd
export WORKING_DIR=$CI_DIR/lattice/build
mkdir -p $WORKING_DIR
pushd $CI_DIR
	mv -v diego-release $WORKING_DIR
	mv -v cf-release $WORKING_DIR
popd

echo "Temporary CI directory: $CI_DIR"
