#!/bin/bash

set -e

pushd diego-release/loggregator
   git fetch
   git checkout origin/master
   git submodule update --init --recursive
popd

#They updated to a version of docker that won't compile with the current diego-release, so we just check out an old, known good SHA
pushd diego-release/src/github.com/docker
    git co 248ec5d74e4f33bbcf946609fc5f9081a267fb8b
popd

diego-lite/diego-lite-pipeline/helpers/run_with_docker \
 diego-lite/compile \
    /workspace/diego-edge \
    /workspace/diego-release \
    /workspace/cf-release \
    /workspace/diego-lite

rm -rf diego-edge.tgz
tar -czf diego-edge.tgz diego-edge
