#!/bin/bash
set -e

cleanup_vagrant() {
    vagrant destroy --force
    rm -f Vagrantfile
}

pushd diego-release/loggregator
   git fetch
   git checkout origin/master
   git submodule update --init --recursive
popd

VAGRANT_BOX_NAME_OR_PATH=$1

if [ -z "$1" ]; then
    VAGRANT_BOX_NAME_OR_PATH="ubuntu/trusty64"
fi

if [ -n "$2" ]; then
    echo "Setting Virtualbox machine folder to $2/virtualbox_vms"

    mkdir -p $2/vagrant_home
fi

trap cleanup_vagrant EXIT

rm -f Vagrantfile
vagrant init $VAGRANT_BOX_NAME_OR_PATH --minimal
vagrant up --provider=virtualbox


vagrant ssh -c "/vagrant/diego-lite/diego-lite-pipeline/01_packaging/install_on_vagrant"

rm -f diego-lite.box
vagrant package --output diego-lite.box
