#!/bin/bash

set -e

generate_terraform_configuration_file(){
    if [ "$1" == "--without-outputs" ]; then
        terraform_outputs=""
    else
        terraform_outputs=',
        "output": {
                    "lattice_target": {
                        "value": "${module.lattice-google.lattice_target}"
                    },
                    "lattice_username": {
                        "value": "${module.lattice-google.lattice_username}"
                    },
                    "lattice_password": {
                        "value": "${module.lattice-google.lattice_password}"
                    }
        }'
    fi

    printf '{
                "module":{
                    "lattice-google":{
                        "source":"%s",
                        "local_lattice_tar_path": "%s",
                        "gce_account_file": "%s",
                        "gce_client_secrets_file": "%s",
                        "gce_ssh_private_key_file": "%s",
                        "gce_ssh_user": "lattice-pipeline-user",
                        "gce_project": "%s"
                    }
                }%s
            }
            ' \
            "$WORKSPACE_DIR/lattice/terraform/google" \
            "$LATTICE_TAR_PATH" \
            "$TF_WORKING_DIR/gce-account.json" \
            "$TF_WORKING_DIR/gce-client-secrets.json" \
            "$TF_WORKING_DIR/gce-ssh-key" \
            "$(cat $TF_WORKING_DIR/gce-project)" \
            "$terraform_outputs" \
            > $TF_WORKING_DIR/lattice.tf
    sync

    echo "== lattice.tf =="
    cat  $TF_WORKING_DIR/lattice.tf | nl
    echo "===="
}

deploy_lattice() {
    pushd $TF_WORKING_DIR
        terraform get -update
        terraform apply || {echo "=====>First terraform apply failed. Retrying...\n"; terraform apply}
    popd
}

download_gce_account_files(){
    aws s3 cp s3://lattice-gocd/credentials/gce-credentials.tar - | tar -xf - -C $TF_WORKING_DIR
#    chmod 600 $TF_WORKING_DIR/ec2-west-1.pem
}

cleanup(){
    set +e
    echo "Cleaning up terraform and related artifacts"
    pushd $TF_WORKING_DIR
        #Terraform has a bug in it where it sees output variables as dependent on resources, but does not destroy them
        #in the correct order. see: https://github.com/hashicorp/terraform/issues/522 . The work-around is to
        #remove the outputs from the local copy of the lattice module and the dependent outputs from the lattice.tf configuration file.
        find -L ./.terraform/modules/ -name "outputs.tf" -exec rm -- {} +
        generate_terraform_configuration_file --without-outputs
        echo "Destroying once (deletes the instances, but fails to delete all network resources)..."
        terraform destroy -force
        echo "Destroying one more time to get rid of the remaining network resources..."
        terraform destroy -force
    popd

    rm -rfv $TF_WORKING_DIR
}

export DIEGO_RELEASE_PATH=$1
export LATTICE_TAR_PATH=$2
WORKSPACE_DIR=`pwd`

TF_WORKING_DIR=/var/tf-working #This is NOT within the shared folder mounted by docker, so that it goes away every run
mkdir -pv $TF_WORKING_DIR

trap cleanup EXIT

download_gce_account_files

generate_terraform_configuration_file

deploy_lattice

source $(dirname $0)/helpers/setup_whetstone
setup_whetstone

PATH=$PATH:$GOPATH/bin ginkgo -noColor -v $GOPATH/src/github.com/pivotal-cf-experimental/whetstone -- \
    -domain=$(cd $TF_WORKING_DIR && terraform output lattice_target) \
    -timeout=300 \
    -username=$(cd $TF_WORKING_DIR && terraform output lattice_username) \
    -password=$(cd $TF_WORKING_DIR && terraform output lattice_password)
