// generated by stringer -type=TaskState; DO NOT EDIT

package models

import "fmt"

const _TaskState_name = "TaskStateInvalidTaskStatePendingTaskStateRunningTaskStateCompletedTaskStateResolving"

var _TaskState_index = [...]uint8{0, 16, 32, 48, 66, 84}

func (i TaskState) String() string {
	if i < 0 || i+1 >= TaskState(len(_TaskState_index)) {
		return fmt.Sprintf("TaskState(%d)", i)
	}
	return _TaskState_name[_TaskState_index[i]:_TaskState_index[i+1]]
}
