#!/bin/bash

set -e

export $(cat /var/lattice/setup)

agent_ctl=/var/vcap/jobs/consul_agent/bin/agent_ctl
sed -i 's/expected=0/expected=1/' "$agent_ctl"
sed -i 's/consul_join=""/consul_join="'$BRAIN_IP'"/' "$agent_ctl"
sed -i 's/consul_server_ips=""/consul_server_ips="'$BRAIN_IP'"/' "$agent_ctl"
sed -i "s/NODE_NAME='lattice-cell-0'/NODE_NAME='$CELL_ID'/" "$agent_ctl"

consul_config=/var/vcap/jobs/consul_agent/config/config.json
consul_config_json=$(cat "$consul_config")
echo $consul_config_json | jq '. + {"retry_join": ["'$BRAIN_IP'"], "node_name": "'$CELL_ID'"}' > "$consul_config"

job_files=$(find /var/vcap/jobs/*/ -type f)
old_brain_ip=$(cat /var/lattice/brain_ip)
perl -p -i -e "s/$old_brain_ip/$BRAIN_IP/g" $job_files
perl -p -i -e "s/lattice-cell-0/$CELL_ID/g" $job_files

perl -p -i -e "s/agent-id-lattice-cell-0/$CELL_ID/g" /etc/{hosts,hostname}
hostname "$CELL_ID"
