#!/bin/bash

set -e

export CI_DIR=$1

LATTICE_DIR=$(cd `dirname $0` && cd ../../.. && pwd)
source $LATTICE_DIR/pipeline/local/env

export LATTICE_SRC_PATH=/run
export DIEGO_RELEASE_PATH=/run/build/diego-release

DOCKER_MOUNT_DIR=$CI_DIR/lattice $CI_DIR/lattice/pipeline/helpers/run_with_docker /run/pipeline/01_compilation/compile_ltc

