#!/bin/bash

if [ -f "$LOCAL_LATTICE_TAR_PATH" ]; then
    if [ "$LOCAL_LATTICE_TAR_PATH" == ".lattice/lattice.tgz" ]; then
        lattice_git_version=$(cat $LATTICE_VERSION_FILE_PATH)
        lattice_tar_version=$(tar xOzf $LOCAL_LATTICE_TAR_PATH lattice-build/common/LATTICE_VERSION)
        if [ "$lattice_git_version" != "$lattice_tar_version" ]; then
            echo "========================================================"
            echo "Local version of Lattice differs from expected version."
            echo "If you want to redownload lattice, delete the .lattice folder and try again."
            echo "========================================================"
        fi
    fi
else
    mkdir -p .lattice

    lattice_tar_version=$(cat $LATTICE_VERSION_FILE_PATH)

    if egrep '\-[[:digit:]]+-g[0-9a-fA-F]{7,10}$' $LATTICE_VERSION_FILE_PATH; then # unstable versions match `git describe` format
        lattice_download_url="https://s3-us-west-2.amazonaws.com/lattice/unstable/$lattice_tar_version/lattice.tgz"
    else
        lattice_download_url="https://s3-us-west-2.amazonaws.com/lattice/releases/$lattice_tar_version/lattice.tgz"
    fi

    echo "Downloading Lattice Release tar from $lattice_download_url => $(pwd)/.lattice/lattice.tgz"
    pushd .lattice > /dev/null
        curl -sOL $lattice_download_url
    popd > /dev/null
    echo "Download complete"
fi
