#!/bin/bash

if [ -f "$LOCAL_LATTICE_TAR_PATH" ]; then
    echo "Found existing lattice tar at $LOCAL_LATTICE_TAR_PATH"
    echo "If you want to redownload lattice, delete the .lattice folder and try again."
else
    mkdir -p .lattice

    lattice_tar_version=$(cat $LATTICE_VERSION_FILE_PATH)

    if egrep '\-[[:digit:]]+-g[0-9a-fA-F]{7,10}$' $LATTICE_VERSION_FILE_PATH; then # unstable versions match `git describe` format
        lattice_download_url="https://s3-us-west-2.amazonaws.com/lattice/unstable/$lattice_tar_version/lattice.tgz"
    else
        lattice_download_url="https://s3-us-west-2.amazonaws.com/lattice/releases/$lattice_tar_version/lattice.tgz"
    fi

    echo "Downloading Lattice Release tar from $lattice_download_url => $(pwd)/.lattice/lattice.tgz"
    pushd .lattice > /dev/null
        curl -sOL $lattice_download_url
    popd > /dev/null
    echo "Download complete"
fi
