#!/bin/bash

tmp_tar_path=$(cd $(dirname "$1") && pwd )/$(basename "$1")
lattice_download_url=$2

if [ -z "$lattice_download_url" ]; then
  echo "ERROR: lattice_tar_source must be set in lattice.*.tf"
  exit 1
else
  rm -f "$tmp_tar_path" > /dev/null
  if [ `echo "$lattice_download_url" | grep -E '^[a-zA-Z0-9]+://.+'` ]; then
    touch "$tmp_tar_path"
  else
    lattice_tar_path="$(cd $(dirname $lattice_download_url) && pwd )/$(basename $lattice_download_url)"
    ln -s "$lattice_tar_path" "$tmp_tar_path"
  fi
fi
