// This file was generated by counterfeiter
package fake_receptor_client_creator

import (
	"sync"

	"github.com/cloudfoundry-incubator/lattice/ltc/receptor_client"
	"github.com/cloudfoundry-incubator/receptor"
)

type FakeCreator struct {
	CreateReceptorClientStub        func(target string) receptor.Client
	createReceptorClientMutex       sync.RWMutex
	createReceptorClientArgsForCall []struct {
		target string
	}
	createReceptorClientReturns struct {
		result1 receptor.Client
	}
}

func (fake *FakeCreator) CreateReceptorClient(target string) receptor.Client {
	fake.createReceptorClientMutex.Lock()
	fake.createReceptorClientArgsForCall = append(fake.createReceptorClientArgsForCall, struct {
		target string
	}{target})
	fake.createReceptorClientMutex.Unlock()
	if fake.CreateReceptorClientStub != nil {
		return fake.CreateReceptorClientStub(target)
	} else {
		return fake.createReceptorClientReturns.result1
	}
}

func (fake *FakeCreator) CreateReceptorClientCallCount() int {
	fake.createReceptorClientMutex.RLock()
	defer fake.createReceptorClientMutex.RUnlock()
	return len(fake.createReceptorClientArgsForCall)
}

func (fake *FakeCreator) CreateReceptorClientArgsForCall(i int) string {
	fake.createReceptorClientMutex.RLock()
	defer fake.createReceptorClientMutex.RUnlock()
	return fake.createReceptorClientArgsForCall[i].target
}

func (fake *FakeCreator) CreateReceptorClientReturns(result1 receptor.Client) {
	fake.CreateReceptorClientStub = nil
	fake.createReceptorClientReturns = struct {
		result1 receptor.Client
	}{result1}
}

var _ receptor_client.Creator = new(FakeCreator)
