---
platform: linux
image: docker:///cloudfoundry/lattice-pipeline
inputs:
- name: lattice
run:
  path: lattice/concourse/tasks/unit-test-cell-helper/run.sh
  params:
    CELL_HELPER: some-cell-helper
